### ISSUE TITLE
Configuring down link and uplink freq with earfcn

### ISSUE THREAD

**Issue by richie777cfc** [srsLTE/srsLTE#117]
srsUE automatically takes dl and up frequency as 2844.1 MHz when using earfcn as 38800. My network is having frequency as 2300 MHz. My devcies are able to latch to that network but here I'm unable to establish a connection with USRP N210. How to configure frequency?

**Comment by ismagom** [comment]
EARFCN 38800 is for TDD mode. srsLTE does not support TDD mode yet.
