### ISSUE TITLE
GTPU Waiting for read

### ISSUE THREAD

**Issue by tanatosos** [srsLTE/srsLTE#118]
Hello,

I've managed to get srsLTE to work properly with bladeRF.
My goal is to stream video from my phone to laptop over LTE.
My lack of knowledge is preventing to move further. Let me expain
you what I have so far and I hope someone might help me.

```
[enb]
enb_id = 0x19B
cell_id = 0x01
phy_cell_id = 1
tac = 0x0007
mcc = 001
mnc = 01
mme_addr = 192.168.1.59
gtp_bind_addr = 192.168.1.187
n_prb = 25
```
When I try to connect my phone here's the message that I got.
```
21:47:23.825528 [S1AP] Info    Connecting to MME 192.168.1.59:36412
21:47:23.827453 [GTPU] Debug   Waiting for read...
```

I've seen that MME is  Mobility Management Entity and MEE is in charge for authentication. What I don't understand is where should I configure MEE (how to add my IMSI number and key).  As I can see the MEE is totally different module and not part of the enodeb. I've randomly assigned MME IP address.

Also, what should be my `gtp_bind_addr`? Right now I'm using IP assigned to my laptop.

**Comment by ismagom** [comment]
srsLTE does not provide an MME. You need to find an 3rd party one.
