### ISSUE TITLE
Throw std::length_error

### ISSUE THREAD

**Issue by liuzhikui** [srsLTE/srsLTE#123]
When I run srsue and srsenb in differemt hosts, sometimes throw std::length_error in UE or in ENB.

**Comment by ismagom** [comment]
can you be more precise please? Can you paste backtrace for instance?

**Comment by liuzhikui** [comment]
Hello, here is backtrace.

**Comment by liuzhikui** [comment]
Hello, here is backtrace:
![2017-11-24 10_50_15 _______________](https://user-images.githubusercontent.com/28185487/33202887-0ee73b3a-d139-11e7-861e-66a8b50057aa.png)

**Comment by ismagom** [comment]
This is an issue with the USRP or USB driver.
