### ISSUE TITLE
UE CQI

### ISSUE THREAD

**Issue by OmarEltobgy** [srsLTE/srsLTE#124]
How can we change the UE CQI, is there any mobility models implemented ? 

Best Regards,
Omar Eltobgy

**Comment by ismagom** [comment]
UE CQI is derived from SNR in https://github.com/srsLTE/srsLTE/blob/344ace8f52289c50caf61459cb5ff6ddec891fe4/lib/src/phy/phch/cqi.c#L280

Next time, please use the mailing list for questions and github issues for issues. Thanks
