### ISSUE TITLE
When I set n_prb=6 in enb.conf file, using one user to  receive downlink data but transform rate is pretty low

### ISSUE THREAD

**Issue by liuzhikui** [srsLTE/srsLTE#129]

**Comment by ismagom** [comment]
What do you mean by transform rate? Can you attach enb.log and be more precise please?

**Comment by liuzhikui** [comment]
The brate is low using USRP B210 as UE when recieving downlink data.

**Comment by liuzhikui** [comment]
The brate is printed by using debug command 't'

**Comment by liuzhikui** [comment]
The brate is printed by using debug command 't'.
