### ISSUE TITLE
Failed to connect to MME - retrying in 10 seconds

### ISSUE THREAD

**Issue by BorjanEch0** [srsLTE/srsLTE#130]
Hello, i get this error every time i start the enodeb please help me i am using bladerf x40

**Comment by mrlnc** [comment]
You need a EPC up and running, e.g. from the OpenAirInterface project. Then you can configure MME IP address in `enb.conf`. srsLTE offers eNodeB, but no core network functionality. 

srsenb will then forward NAS messages to the MME (like Auth Request, or Attach Request).

**Comment by BorjanEch0** [comment]
understood. thank you for the information it is much appreciated
