### ISSUE TITLE
Hardcoded RRC establishment cause in S1AP InitialUEMessage

### ISSUE THREAD

**Issue by svwi** [srsLTE/srsLTE#131]
The UE signalled RRC establishment cause is not included in the eNB's S1AP InitialUEMessage, instead mo-Signalling is hardcoded.

This leads to an issue observed when using srsENB with a Huawei E392 dongle and openEPC v7.1 by Core Network Dynamics. The dongle's initial NAS message is a Service Request with RRC cause mo-Data, which gets rejected by the EPC due to a failed sanity check according to TS 24.301 Table D.1.1

Including the UE signalled RRC establishment cause fixes this issue (see attached patch).
[rrc_est_cause_s1ap.txt](https://github.com/srsLTE/srsLTE/files/1578667/rrc_est_cause_s1ap.txt)

**Comment by andrepuschmann** [comment]
Fixed in new release.
