### ISSUE TITLE
M-TMSI config deprecated

### ISSUE THREAD

**Issue by mrlnc** [srsLTE/srsLTE#143]
This and following lines in default configuration are unused since NAS stores the security context in `.ctxt` file.
https://github.com/srsLTE/srsLTE/blob/dfe430a584d3d73c217046b48c8abaf83a67d079/srsue/ue.conf.example#L115
I've added a config to ignore reading the `ctxt` file to enforce 'clean' IMSI attaches. Not sure if the functionality is something others want. Also, if users wish to manually set the M-TMSI, the `.ctxt` file is kind of malformatted:
https://github.com/srsLTE/srsLTE/blob/dfe430a584d3d73c217046b48c8abaf83a67d079/srsue/src/upper/nas.cc#L1004
`uint32_t ctxt.guti.m_tmsi` is casted to `signed int`. That's only a problem if somebody want's to manually enforce a M-TMSI.

**Comment by suttonpd** [comment]
Thanks Merlin - we've removed those lines in the default config. For users who want to force the IMSI attach, it's easier to simply delete the .ctxt file.
