### ISSUE TITLE
pdsch_ue fails to decode CFI correctly

### ISSUE THREAD

**Issue by naziask** [srsLTE/srsLTE#147]
pdsch_enodeb is using constant CFI (cfi=2) in all subframes. However, in the UE logs we see different CFI values:
[INFO]: Decoded CFI=3 with correlation 5.65, sf_idx=3
[INFO]: Searching DL C-RNTI Format1A in 16 ue locations
[INFO]: Searching DL C-RNTI Format1  in 16 ue locations
[INFO]: Searching DL C-RNTI in 6 ue locations, format 1A
O[INFO]: Decoded CFI=1 with correlation 5.58, sf_idx=4
[INFO]: Searching DL C-RNTI Format1A in 12 ue locations
[INFO]: Searching DL C-RNTI Format1  in 12 ue locations
[INFO]: PSS: id=0, peak_pos=397, peak_value=14.735041
[INFO]: PSS-CFO: filter=yes, estimated=0.738486, mean=0.003154
[INFO]: Warning: Expected SF idx 5 but got 0! (0 frames)

Following are the test setup details:
 USRP B210 SDRs and a wired RF cable between Tx and Rx antenna ports.

**Comment by ismagom** [comment]
As you can see in the log:

[INFO]: Searching DL C-RNTI in 6 ue locations, format 1A
O[INFO]: Decoded CFI=1 with correlation 5.58, sf_idx=4
[INFO]: Searching DL C-RNTI Format1A in 12 ue locations

You are receiving and Overflow message ('O') from the USRP. The UE then
looses synchronization and fails to decode CFI.
