### ISSUE TITLE
UE support eMBMS

### ISSUE THREAD

**Issue by omario61** [srsLTE/srsLTE#162]
Does the provided UE  support listening on eMBMS  channels?

**Comment by andrepuschmann** [comment]
Hey, with the current version there is only eMBMS support in the PHY-layer UE, i.e. pdsch_ue. Full support for srsUE with be coming in the next release.

**Comment by suttonpd** [comment]
The next release will be 18_06  in June. Please use our mailing list for further questions - details are are in the project readme.
