### ISSUE TITLE
epc shuts down on SIGPIPE on Fedora 27

### ISSUE THREAD

**Issue by jgiovatto** [srsLTE/srsLTE#165]
restarting enb eventually causes epc to receive SIGPIPE which is fatal.
1) start epc, enb, ue, wait for connection
2) kill ue, enb,
3) start enb, ue new session in epc receives SIGPIPE which is fatal.

gdb initially catch SIGPIPE in a send call

```
Thread 2 "srsepc" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7ffff5966700 (LWP 29037)]
0x00007ffff7bcbee4 in __libc_sendmsg (fd=3, msg=msg@entry=0x7ffff57144b0, flags=flags@entry=0) at ../sysdeps/unix/sysv/linux/sendmsg.c:28
28	  return SYSCALL_CANCEL (sendmsg, fd, msg, flags);
```

Workaround below using SIG_IGN.
Found that setting MSG_NOSIGNAL as the last arg in the sctp_send did NOT work as expected.

```diff --git a/srsepc/src/main.cc b/srsepc/src/main.cc
index e2c00675..074cf008 100644
--- a/srsepc/src/main.cc
+++ b/srsepc/src/main.cc
@@ -275,6 +275,7 @@ main (int argc,char * argv[] )
   signal(SIGINT, sig_int_handler);
   signal(SIGTERM, sig_int_handler);
   signal(SIGKILL, sig_int_handler);
+  signal(SIGPIPE, SIG_IGN);

   all_args_t args;
   parse_args(&args, argc, argv); 
diff --git a/srsepc/src/mme/mme.cc b/srsepc/src/mme/mme.cc
index 1a385d8d..1c960b1a 100644
--- a/srsepc/src/mme/mme.cc
+++ b/srsepc/src/mme/mme.cc
@@ -135,6 +135,11 @@ mme::run_thread()
     m_s1ap_log->debug("Waiting for SCTP Msg\n");
     pdu->reset();
     rd_sz = sctp_recvmsg(s1mme, pdu->msg, sz,(struct sockaddr*) &enb_addr, &fromlen, &sri, &msg_flags);
+
+    if (errno == EPIPE){
+      m_s1ap_log->warning("Previous connection broken from SCTP socket\n");
+    }
+
     if (rd_sz == -1 && errno != EAGAIN){
       m_s1ap_log->error("Error reading from SCTP socket: %s", strerror(errno));
     }
```

EPIPE is seen in the next successful read of a new session but not immediately obvious to the caller with rd_sz > 0.

```
8:08:52.432798 [S1AP] [D] Waiting for SCTP Msg
18:08:52.631697 [S1AP] [W] Previous connection broken from SCTP socket
18:08:52.631765 [S1AP] [I] Received S1AP msg. Size: 38
18:08:52.631794 [S1AP] [I] Received Succeseful Outcome PDU
18:08:52.631815 [S1AP] [I] Received Initial Context Setup Response.
```

**Comment by andrepuschmann** [comment]
Thanks for spotting this. @alvasMan can we reproduce this with Ubuntu?

**Comment by jgiovatto** [comment]
FYI, seems to only be an issue on the epc. Restarting the epc does not seem to effect the enb.

**Comment by alvasMan** [comment]
No I can't seem to replicate this behavior in Ubuntu 16.04.
I'll investigate this next week on a Fedora machine. @jgiovatto does this *always* happens? Or just sometimes?

**Comment by jgiovatto** [comment]
Happens every time.

**Comment by eschreiber-alink** [comment]
I'm able to reproduce on Ubuntu 16.04 by running srsepc in gdb ...

# gdb sudo srsepc
(gdb) run epc.conf

Then same sequence as initially reported:
1. start enb, ue, wait for connection
2. kill ue, kill enb
3. start enb, start ue

Thread 3 "srsepc" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7ffff6077700 (LWP 11847)]
0x00007ffff7bcaa6d in sendmsg () at ../sysdeps/unix/syscall-template.S:84

**Comment by alvasMan** [comment]
Joe, are you sure that the steps to replicate this are not the following:

1 - Startup EPC, eNB and UE
2 - Kill eNB first, UE second.
3 - Restart eNB and UE?

There was a bug in the EPC where the EPC did not clean the UE context properly when the eNB was terminated while having users attached. If that is the issue, it will be fixed in the next release.

**Comment by jgiovatto** [comment]
You may be correct, with the order above I do see SIGPIPE, when only enb ue interaction then no issues seen.

**Comment by andrepuschmann** [comment]
Fixed in new release,
