### ISSUE TITLE
Support for Ettus N310

### ISSUE THREAD

**Issue by vithyatith** [srsLTE/srsLTE#171]
Hi,

Has anybody try getting this to work on the Ettus N310? This is fairly a new product from Ettus. I can't figure out the correct sampling rate without getting a lot of under runs.

**Comment by andrepuschmann** [comment]
Ettus didnt send us one yet ;-) but I'd say the standard 30.72 MHz clock rate should do the trick. You have to specify it manually though.

**Comment by ttsou** [comment]
N310 supports rates derived from a 122.88 MHz  clock (30.72 MHz * 4). Radix-3 FFT rates are not supported. Recommended LTE sample rates are below.

```
BW (MHz)  Sample Rate (Msps)
  1.4           1.92
  3             3.84
  5             7.68
  10           15.36
  15           15.36/30.72
  20           30.72
```
I can submit a patch when I'm back in the lab next week.

**Comment by vithyatith** [comment]
Thanks Tom, I tried and still having issue. Maybe I'm not putting in the right place. I will wait to try your patch. 
Thanks

**Comment by vithyatith** [comment]
Tom or Andre,

I'm getting stuck in getting SrsLTE to work. 

Below are the output and the code changes I had made. I tried both sample rate of 15.36e6 and 30.73e6 and still doesn't work. Any suggestions?

//////////////////////////////// 
Output when I run srsenb for bandwidth 10Mhz

[INFO] [MPMD] Initializing 1 device(s) in parallel with args: mgmt_addr=192.168.10.2,type=n3xx,product=n310,serial=3145FA5,claimed=False,addr=192.168.10.2,master_clock_rate=122880000
[INFO] [MPM.PeriphManager] init() called with device args `mgmt_addr=192.168.10.2,product=n310,master_clock_rate=122880000'.
[INFO] [RFNOC DMA FIFO] Running BIST for FIFO 0... 
[INFO] [RFNOC DMA FIFO] BIST passed (Throughput: 1339 MB/s)
[INFO] [RFNOC DMA FIFO] Running BIST for FIFO 1... 
[INFO] [RFNOC DMA FIFO] BIST passed (Throughput: 1316 MB/s)
[INFO] [RFNOC DMA FIFO] Running BIST for FIFO 2... 
[INFO] [RFNOC DMA FIFO] BIST passed (Throughput: 1341 MB/s)
[INFO] [RFNOC DMA FIFO] Running BIST for FIFO 3... 
[INFO] [RFNOC DMA FIFO] BIST passed (Throughput: 1341 MB/s)
[INFO] [RFNOC RADIO] Register loopback test passed
[INFO] [RFNOC RADIO] Register loopback test passed
[INFO] [RFNOC RADIO] Register loopback test passed
[INFO] [RFNOC RADIO] Register loopback test passed
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed
[INFO] [CORES] Performing timer loopback test... 
[INFO] [CORES] Timer loopback test passed

==== eNodeB started ===
Type <t> to view trace
SSULLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL

//////////////////////////////// 
Code mode.

File rf_uhd_imp.c

      // Added this condition around line 441  
      else if (find_string(devices_str, "type=n3xx")) {
              printf("VT got the type n3xxx ....");

              args = "type=n3xx,master_clock_rate=122880000";
                      handler->current_master_clock = 122880000;
                      handler->dynamic_rate = false;
                      handler->devname = DEVNAME_N3XX;
     }


- File txrx.cc 
void txrx::run_thread()
{
  phch_worker *worker = NULL;
  cf_t *buffer[SRSLTE_MAX_PORTS] = {NULL};
  srslte_timestamp_t rx_time, tx_time; 
  uint32_t sf_len = SRSLTE_SF_LEN_PRB(worker_com->cell.nof_prb);
  
  float samp_rate = srslte_sampling_freq_hz(worker_com->cell.nof_prb);
  samp_rate = 15.36e6; // Hard code it and tried both 30.72e6 and 15.36e6

**Comment by ismagom** [comment]
You can't change the sampling rate like that because FFT sizes need to change too. Enable cmake option USE_LTE_RATES and recompile. It should use default radix-2 sizes

**Comment by ttsou** [comment]
Pull request https://github.com/srsLTE/srsLTE/pull/176 for N310 support is up for review. Note that issue #175 is currently blocking.

**Comment by andrepuschmann** [comment]
Closing as will be fixed through UHD.
