### ISSUE TITLE
Package of teid and corresponding is error!

### ISSUE THREAD

**Issue by liuzhikui** [srsLTE/srsLTE#178]
I observed that package of teid in send_initial_context_setup_request() in s1ap_ctx_mngmt_proc.cc file and corresponding parsing in setup_erabs() in rrc.cc file(enb side)is not right.

there is code in in send_initial_context_setup_request() in s1ap_ctx_mngmt_proc.cc file:
_**uint32_t sgw_s1u_teid = erab_ctx->sgw_s1u_fteid.teid; 
memcpy(erab_ctx_req->gTP_TEID.buffer, &sgw_s1u_teid, sizeof(uint32_t));**_

and corresponding code used to parse teid is there:
**_uint32_t teid_out;
uint8_to_uint32(erab->gTP_TEID.buffer, &teid_out);_**

I modified the latter as:
**_uint32_t teid_out;_**
**_memcpy(&teid_out, erab->gTP_TEID.buffer, sizeof(uint32_t));_**

**Comment by andrepuschmann** [comment]
Thanks for that. Will be fixed in the next release.
