### ISSUE TITLE
Scheduling request if periodicity = 5ms is wrong

### ISSUE THREAD

**Issue by Richard-Stenzel** [srsLTE/srsLTE#179]
Hi!

I noted in the srsUE log that I get a wrong I_sr when I set sched_request_cnfg ={ ... period = 5 ... } in rr.conf. For example I got I_sr=5 while it should be between 0-4 as in 36.213:

![36.213 10.1.5](https://user-images.githubusercontent.com/38288345/40532258-262eefcc-5fff-11e8-8dfe-f891d7d80313.png)

The error might be in /srsenb/src/upper/rrc.cc in lines 1674-1679: 
```
if (parent->cfg.sr_cfg.sf_mapping[j_min] < period) {
    if (period > 5) {
        *I_sr = period - 5 + parent->cfg.sr_cfg.sf_mapping[j_min]; 
    } else {
        *I_sr = period + parent->cfg.sr_cfg.sf_mapping[j_min]; 
    }
```
If period is set to 5 then the code of the else statement will be executed which is then wrong (as seen in the table). IMO it should also be ```*I_sr = period - 5 + parent->cfg.sr_cfg.sf_mapping[j_min];``` or just ```*I_sr = parent->cfg.sr_cfg.sf_mapping[j_min];``` for ```period = 5```.

Kind regards,
Richard

**Comment by andrepuschmann** [comment]
Resolved in next, thanks.
