### ISSUE TITLE
UB with msg->msg in liblte

### ISSUE THREAD

**Issue by SoniEx2** [srsLTE/srsLTE#181]
liblte has UB:

```C++
uint8 *msg_ptr = msg->msg;
if (msg != NULL) {
    // ...
}
```

Your usual compiler just optimizes away the `msg != NULL` check, but this is straight-up UB.

**Comment by suttonpd** [comment]
Fixed for next release

**Comment by SoniEx2** [comment]
could you also include tests for calling them with various sets of null/non-null arguments, and expected results?
