### ISSUE TITLE
bler goes high when srsue exceeds fixed UL MCS

### ISSUE THREAD

**Issue by nitha2000** [srsLTE/srsLTE#182]
Hi,
I fixed the maximum UL_MCS at Amarisoft enb to be 16, and I set the gains accordingly so the link can operate at this MCS. The issue is that srsue operates at MCS 16 for most part with bler is less than 1-2%. However, very often the MCS jumps to 17/18/20/21 and during this time ul_bler goes 20-60%, and throughput is reduced significantly.  I'm wondering why it happens and is there a way to fix the MCS ?
thanks,

**Comment by andrepuschmann** [comment]
It's the eNBs task to assign MCS for the UL. In your case it means that the channel is not good enough to do higher MCSs.
