### ISSUE TITLE
Error reading user database file user_db.csv

### ISSUE THREAD

**Issue by mdasari823** [srsLTE/srsLTE#186]
I compiled and installed srsLTE successfully. I am unable to execute it because this issue. Any help?
     
    ---  Software Radio Systems EPC  ---
    Reading configuration file srsepc/epc.conf...
    Error reading user database file user_db.csv
    Error initializing HSS

**Comment by Bobavince** [comment]
Did you create the user_db.csv file ? (in /srsepc)

**Comment by mdasari823** [comment]
Aah, thanks a lot. My bad, I was debugging by printfs in the code, but prints are disabled it seems. The problem solved. It is just a path problem then. Thank you.

**Comment by Avatarrunt** [comment]
how did you fix it

**Comment by EhsaanIlyas456** [comment]
How did you fix it?
