### ISSUE TITLE
Time Advance Issue???

### ISSUE THREAD

**Issue by michalakisk** [srsLTE/srsLTE#190]
Hi,
I am using srsENB to get the TA which is assigned to the UE. 
I am using USRP B205mini-i as my SDR platform.
After bringing up the cell and trying to perform attachment from a very short distance [4 meters], I get an unexpected time advance value of 4, which sometimes can get 5 depending on the run. 
I am not sure if this is a hardware issue or is it the software.
Can you please guide me on how to approach this issue?

This is what I get: [note these are additions I made to print TA in terminal window]

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Timing Advance: 4 [Preable Idx: 36]
 RNTI: 75 ====================
SCHED: Could not transmit RAR within the window (RA TTI=9831, Window=10, Now=9850)
Disconnecting rnti=0x4b.
RACH:  tti=9951, preamble=27, offset=13, temp_crnti=0x4c
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Also,
I have noticed than when trying to increase the number of resource blocks from 50 to 75 or 100, the cell never brings up and the code crushes without indicating any error. This happens even when using 50 sometimes. 

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
Reading configuration file enb.conf...
Opening USRP with args: type=b200,master_clock_rate=30.72e6
-- Detected Device: B205mini
-- Operating over USB 3.
-- Initialize CODEC control...
-- Initialize Radio control...
-- Performing register loopback test... pass
-- Performing CODEC loopback test... pass
-- Asking for clock rate 30.720000 MHz... 
-- Actually got clock rate 30.720000 MHz.
-- Performing timer loopback test... pass
Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz
Failed to connect to MME - retrying in 10 seconds
Setting Sampling frequency 11.52 MHz

==== eNodeB started ===
Type <t> to view trace
srsLTE crashed... backtrace saved in './srsLTE.backtrace.crash'...
---  exiting  ---
pure virtual method called
terminate called without an active exception
srsLTE crashed... backtrace saved in './srsLTE.backtrace.crash'...
---  exiting  ---
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

**Comment by andrepuschmann** [comment]
Hey, first of all it seems there is an issue with connecting to the EPC in your run. Regarding the TA, I assume you use srsUE+B210 or similar as UE. In this case, a TA of 4 or 5 is normal because of an uncalibrated Rx/Tx time offset, so no need to worry and no issue at all.

**Comment by michalakisk** [comment]
Thanks for your feedback.
I haven't connected EPC since I don't need it for my experiments.
Can you please guide me on how to calibrate my Rx and Tx paths? I have a
b205mini-i which I guess has similar RF characteristics as b210 considering
they use the same RFIC from AD.
The UE I am using is a COTS UE.

Thanks again
Michalis
