### ISSUE TITLE
creating dedicated bearer 

### ISSUE THREAD

**Issue by dineshpv** [srsLTE/srsLTE#191]
Hi,
Can srsLTE handle creation of dedicated radio bearer? If so, could you please help with the steps to create a dedicated radio bearer from the network side.

P.S: We are using Nextepc as the core network for our scenario.

Regards,
Dinesh

**Comment by ismagom** [comment]
Not an issue. Thanks

**Comment by dineshpv** [comment]
According the issue #100 , it was mentioned that using of dedicated bearers is not available back then.
Could you please tell me, if this feature is included in the latest version?

Thanks in advance.

**Comment by andrepuschmann** [comment]
No, it's not.
