### ISSUE TITLE
Licensed frequency conflict problem ?

### ISSUE THREAD

**Issue by Raw1mage** [srsLTE/srsLTE#205]
I was testing srsenb with b210 operating in band3 overlapped with the commercially licensed band.
Huawei dongle works, but Android phones cannot attach.
I installed "network cell info lite" on Android to observe the signal strength from the eNB, and found issues.

The eNB generates valid strong signal (-60dBm) only for 2 seconds after the initialization, and soon dropped below -140 dBm which is unusable for any phone. 

The odd thing is that Huawei dongle can keep the connection and transmit/receive normally.
However none of the android phones can work with such a weak signal.

My question is, is srseNB dropping the signal strength because it detects the conflict with commercial eNB ?

**Comment by Raw1mage** [comment]
This issue is directed less to srsLTE enb.conf
all kinds of variable settings cannot change the phenomenon of weak signals.
Nevertheless, if anyone ever solved the similar situation, a little light is appreciated.

**Comment by Raw1mage** [comment]
Anyway, my uhd B210 has trouble delivering strong power to establish a stable connection.   I hope there's at least a gain monitoring tool for tuning.

**Comment by andrepuschmann** [comment]
There is no tx power reduction whatsoever in srsENB. Need to reinvestigate whats happening there. Please reopen if needed.
