### ISSUE TITLE
Could not transmit RAR 

### ISSUE THREAD

**Issue by michalakisk** [srsLTE/srsLTE#214]
Hi,
I was facing similar problems in the past however I never resolved them. 

Right now I have two problems: 
1. I am missing some information on how to calibrate b205mini-i Rx/Tx paths in order to get true TA values 
2. I am facing problems with Random Access response message. This has as a result the RRC connection setup procedure to stop at before it even starts.
Here is what I get: 
"
Disconnecting rnti=0x46.
SCHED: Could not transmit RAR within the window (RA TTI=9491, Window=10, Now=9511)
"

I am not sure what causes this RAR issue. I couldn't find anything in the code. I have checked the code and most specifically srsenb/srs/mac/scheduler.cc, where RAR scheduling takes place and I found that the problem arises here:

      /* Check if we are still within the RAR window, otherwise discard it */
      if (current_tti <= (pending_rar[i].rar_tti + cfg.prach_rar_window + 3)%10240 && current_tti >= pending_rar[i].rar_tti + 3)
      {                 
        ...........
      }

Could it be the hardware? I mean the CPU that cause some delays? Or the fact the Rx/Tx paths are not calibrated?

Thanks 
Michalis

**Comment by andrepuschmann** [comment]
Hey Michalis, please have a look and try with the new version. If the issue still exists, please reopen the issue and provide full logs for UE and eNB and exact configuration details.

**Comment by kamgaarnold** [comment]
Hello @andrepuschmann  please i'm facing the same issue as @michalakisk. does it have to do with some config file? i'm using bladeRF_Micro A
