### ISSUE TITLE
Treatment of NAS Counters in nas::parse_security_mode_command()

### ISSUE THREAD

**Issue by cpetersgit** [srsLTE/srsLTE#218]
I've been looking at the treatment of the NAS tx and rx counters in the function nas::parse_security_mode_command() after experiencing a problem with a certain core we tested against.  Can't claim I have an all inclusive solution, but it seems to work with several cores and I believe it satisfies the wording of the spec.

In nas::parse_security_mode_command() on lines 862:864 it says this:
862     // Reset counters (as per 24.301 5.4.3.2) 
863    ctxt.rx_count = 0; 
864    ctxt.tx_count = 0; 

This will reset the NAS counts for any Security Mode Command.  However, the spec says this:

**_The MME shall reset the downlink NAS COUNT counter and use it to integrity protect the initial SECURITY MODE COMMAND message if the security mode control procedure is initiated:
-	to take into use the EPS security context created after a successful execution of the EPS authentication procedure;
-	upon receipt of TRACKING AREA UPDATE REQUEST message including a GPRS ciphering key sequence number IE, if the MME wishes to create a mapped EPS security context (i.e. the type of security context flag is set to "mapped security context" in the NAS key set identifier IE included in the SECURITY MODE COMMAND message)._**

As I read the above, you only want to reset the counter(s) if you had previously executed the Auth Procedure.  If you hadn't you would not reset the counters.  My solution was to add a member variable called auth_requested and set it true in the auth_result == AUTH_OK if statement in nas::parse_authentication_request().  Then in nas::parse_security_mode_command() I changed the code to

  // Reset counters (as per 24.301 5.4.3.2)
  if (this->auth_request)
  {
    ctxt.rx_count = 0;
    ctxt.tx_count = 0;
    this->auth_request = false;
  }

I'm sure there is a more elegant solution, but this allowed correct operation with multiple cores.

**Comment by andrepuschmann** [comment]
Thanks for reporting that. Should be fixed in next release.
