### ISSUE TITLE
multiple enb's

### ISSUE THREAD

**Issue by NateJ3** [srsLTE/srsLTE#223]
Has anyone had success connecting multiple eNodeB's simultaneously using SRS?

Thanks,
Nate

**Comment by NateJ3** [comment]
Was there a response to this issue?  I'm hoping someone can help advise how
to address multiple enb's at the same time.

Thanks,
Nate

Nate Johnson
Field Service Manager
Corrections.com
15 Mill Wharf Plaza, Scituate, MA 02066
617-471-4445 (office)
401-439-5484 (cell)
njohnson@corrections.com

**Comment by ismagom** [comment]
I closed this issue because it's not an issue. For questions use the list please.

**Comment by NateJ3** [comment]
I'm sorry, I'm new to the site.  Can you please direct me to 'the list.'


Thanks,
Nate

Nate Johnson
Field Service Manager
Corrections.com
15 Mill Wharf Plaza, Scituate, MA 02066
617-471-4445 (office)
401-439-5484 (cell)
njohnson@corrections.com

**Comment by suttonpd** [comment]
Hi Nate, the mailing list details can be found here: http://www.softwareradiosystems.com/mailman/listinfo/srslte-users

**Comment by NateJ3** [comment]
Great, thank you

Nate Johnson
Field Service Manager
Corrections.com
15 Mill Wharf Plaza, Scituate, MA 02066
617-471-4445 (office)
401-439-5484 (cell)
njohnson@corrections.com
