### ISSUE TITLE
How to run only EPC on machine and physicaly connect Nokia LTE eNB ?

### ISSUE THREAD

**Issue by hnkakadia** [srsLTE/srsLTE#231]
- I am looking for settings to do on EPC to listen to eNB connected through ethernet cable.
Can someone provide me this information?

**Comment by jgiovatto** [comment]
Have you tried changing 
```
gtpu_bind_addr=127.0.1.100
mme_bind_addr = 127.0.1.100
```
in epc.conf to your eth ip address ?

Also you may want to try the mailing list before posting this as an issue first.
