### ISSUE TITLE
block_queue problems

### ISSUE THREAD

**Issue by adriandab** [srsLTE/srsLTE#244]
I came around two problems with block_queue:

a) wait_pop() uses bzero() to clear the memory of myobj. this works fine, when a struct, but can be fatal with objects, say std::string. pop_() will invoke the copy-constructor at q.front() which segfaults. 
I suggest removing the bzero() call. After all, try_pop() doesn't zero as well.

b) clear() calls try_pop() until empty which actually turns into a infinite loop as try_pop() does not call q.pop() if value is NULL (which it is here). 
I suggest, moving q.pop() in the pop_() method outside of  the if (value) {...} block.

**Comment by andrepuschmann** [comment]
Thanks for that. Will be fixed in next.
