### ISSUE TITLE
uninitialied warning cleanup

### ISSUE THREAD

**Issue by jgiovatto** [srsLTE/srsLTE#249]
Hi folks noticed some possible uninitialized compiler warnings.
Could be a little risky here since return value of pop_ is not consulted.
Added initializer to handle  "ptr" types. 

```
--- a/lib/include/srslte/common/block_queue.h
+++ b/lib/include/srslte/common/block_queue.h
 
   myobj wait_pop() { // blocking pop
-    myobj value;
+    myobj value = myobj();
     pop_(&value, true);
     return value;
   }
```

**Comment by andrepuschmann** [comment]
Thanks Joe. I had already spotted this during the last "clean build" tests but we then forgot about it.I've fixed it now and pushed to master and also tagged the release as 18.09.
