### ISSUE TITLE
srsENB/B210 Tx issue on startup

### ISSUE THREAD

**Issue by ffsv** [srsLTE/srsLTE#251]
Dear team,

I have prepared the next enviroment for LTE Lab:
- Ubuntu 16.04 LTS on VirtualBox with NextEPC as MME and srsENB as eNodeB
- USRP B210 with GPS antenna, SMA Antennas and USB 2.0 with external power.

After srsENB startap with default parameters the S1-MME associoation establishes successfully, but B210 starts with one Rx tranceiver only (I'm observing green LED only on Rx tranceiver without red LED on Tx). 

Should B120 within srsLTE with deault "enb.conf" establish Tx tranceiver too at startup? Could you please help me to investigate an issue?

:~/srsLTE/srsenb$ sudo ../build/srsenb/src/srsenb enb.conf
---  Software Radio Systems LTE eNodeB  ---

Reading configuration file enb.conf...
[INFO] [UHD] linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_3.13.0.1-release
Opening USRP with args: master_clock_rate=30.72e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 2.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 30.720000 MHz... 
[INFO] [B200] Actually got clock rate 30.720000 MHz.
Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Setting Sampling frequency 23.04 MHz

==== eNodeB started ===
Type <t> to view trace
LLLLLLLLOLLLLLLLLLLLLLLLLLLLLLLLLOLLLLLLLLLLL

**Comment by andrepuschmann** [comment]
Closing issue as this is not related to the code. You see lot's of lates, probably your PC is too slow. Try lower number of PRBs.
