### ISSUE TITLE
bit_buffer msg field not initialized in copy operators

### ISSUE THREAD

**Issue by jgiovatto** [srsLTE/srsLTE#252]
Hi,
Looking at byte_buffer_t and bit_buffer_t in lib/include/srslte/common/common.h
looks like msg is not initialized in bit_buffer as it is in byte_buffer ctors.
Possibly use  msg = &buffer[SRSLTE_BUFFER_HEADER_OFFSET] ?
I dont see these 2 operators being used anyplace at the moment.

```
  bit_buffer_t(const bit_buffer_t& buf){
      N_bits = buf.N_bits;
      memcpy(msg, buf.msg, N_bits);
    }
    bit_buffer_t & operator= (const bit_buffer_t & buf){
      // avoid self assignment
      if (&buf == this)
        return *this;
      N_bits = buf.N_bits;
      memcpy(msg, buf.msg, N_bits);
      return *this;
    }
```

**Comment by andrepuschmann** [comment]
Hey Joe, yes, you're right with both. Even though they are not used at the moment they should be correct. Fixed in next.
