### ISSUE TITLE
LIBLTE_ERROR_ENUM liblte_s1ap_pack_pdcp_sn(LIBLTE_S1AP_PDCP_SN_STRUCT *ie,   uint8_t **ptr) function contains error!

### ISSUE THREAD

**Issue by liuzhikui** [srsLTE/srsLTE#253]
Hi, I find that function named **liblte_s1ap_pack_pdcp_sn** in liblte_s1ap.cc file contains error.
in **liblte_value_2_bits(0, ptr, (1*8)-12)**; the second param is negative, that will cause other errors.

**Comment by andrepuschmann** [comment]
You are right. Thanks for spottng this. We'll take care of this.

**Comment by Acciente717** [comment]
Hi there. I spotted this bug too and find this issue already opened here. Hope it will be fixed soon. :)

**Comment by andrepuschmann** [comment]
Thanks. They have been fixed and will be available in the next release.
