### ISSUE TITLE
SIB13 not applied if it is not already present in rrc::configure_serving_cell

### ISSUE THREAD

**Issue by JonathanRennison** [srsLTE/srsLTE#256]
In `rrc::configure_serving_cell`, SIB2 and SIB13 are applied if they are present using `rrc::apply_sib2_configs` and `rrc::apply_sib13_configs` respectively.

In the case where they are not present, they are fetched and when received are processed by `rrc::handle_sib2` and `rrc::handle_sib13` respectively.
`rrc::handle_sib2` calls `rrc::apply_sib2_configs` as expected, however `rrc::handle_sib13` does nothing.

The effect of this is that PMCH decoding and MBMS does not work if the SIB13 had not already been received when `rrc::configure_serving_cell` is called. Calling `rrc::apply_sib13_configs` from `rrc::handle_sib13` fixed the issue here.

**Comment by andrepuschmann** [comment]
Thanks for reporting this Jonathan. We'll look into it.

**Comment by andrepuschmann** [comment]
Fixed in next release.
