### ISSUE TITLE
mch_config() factory default struct has incorrect defaults for um.rx_mod and um.tx_mod

### ISSUE THREAD

**Issue by JonathanRennison** [srsLTE/srsLTE#257]
The `mch_config()` factory method returns a default `srslte_rlc_config_t` instance where `um.rx_mod` and `um.tx_mod` are both set to 1.
This is inconsistent with the values for `um.rx_sn_field_length` and `cfg.um.tx_sn_field_length`, which are set to RLC_UMD_SN_SIZE_5_BITS, which corresponds with a value of 32.
This prevents MCH PDU-> SDU packet reassembly in `rlc_um::rlc_um_rx::reassemble_rx_sdus` from working as a receive window of 1 is used instead of 32.

**Comment by andrepuschmann** [comment]
Thanks for reporting this Jonathan. We'll look into it.

**Comment by andrepuschmann** [comment]
Fixed in next.
