### ISSUE TITLE
srsue::dl_harq_entity::mutex left locked causing deadlock if subframe fails CRC check

### ISSUE THREAD

**Issue by JonathanRennison** [srsLTE/srsLTE#260]
In `srsue::dl_harq_entity::new_grant_dl` the mutex `srsue::dl_harq_entity::mutex` is locked.
It is unlocked in `srsue::dl_harq_entity::tb_decoded`.
If the subframe fails its CRC check, for example due to poor reception, `srsue::dl_harq_entity::tb_decoded` is never called and the UE deadlocks on the next attempt to acquire the mutex.

**Comment by andrepuschmann** [comment]
Thanks for reporting this Jonathan. We'll look into it.

**Comment by JonathanRennison** [comment]
To add some information on this, in our testing this problem has occurred when the warning
> DL PID %d: Size of grant changed during a retransmission

is emitted in `srsue::dl_harq_entity::new_grant_dl`.
Though not all cases where this warning was emitted resulted in a deadlock.

**Comment by andrepuschmann** [comment]
Not an issue, mutex is unlocked later on, see tb_decoded_()
