### ISSUE TITLE
unable to locate package libmedtls

### ISSUE THREAD

**Issue by QasimBM** [srsLTE/srsLTE#269]
I have been trying to get hits library download but I am getting no help. Kindly help me install this library. It keeps giving error unable to locate package. Do I need to install the package first, or do what?

**Comment by andrepuschmann** [comment]
Seems you don't have the header files installed. You need those to build srsLTE. Have you followed the instructions? Please provide the CMake output.

**Comment by QasimBM** [comment]
Issue resolved. I need to download it via 3rd party

**Comment by natanzi** [comment]
I have the same issue, Would you please assist?
