### ISSUE TITLE
Missed subframes with 2 UEs

### ISSUE THREAD

**Issue by igorskh** [srsLTE/srsLTE#272]
Hello,

We have noticed some strange behavior while running downlink test on 2 UEs with iPerf3 and another traffic generator, second connected UE has some subframes missed (further evaluation showed that every 20th subframe is missing).

### Configuration
- srsLTE eNB and srsLTE EPC commit from Mon Oct 15 10:09:39 2018 +0200
- UEs: Samsung Galaxy Tab 3 and OnePlus 6 (and srsUE in the second scenario)
- Traffic generator: iperf3

### First scenario
we have tested the srsLTE eNB and commercial UEs and run iperf3 on the second connected UE:
`iperf3 -c 10.0.0.1 -P10`

The spectrum has a repeating pattern with empty subframes like in the figure below:
![missed-sf1](https://user-images.githubusercontent.com/2114618/49383260-9cfe7e00-f718-11e8-9f56-23a6d5944741.png)

After we reconnect the second UE one or sometime two times the issue disapears:
![iperf](https://user-images.githubusercontent.com/2114618/49383370-de8f2900-f718-11e8-8435-7734998597e3.png)

### Second scenario
We tested with a branch with our changes in a code to use bandwidth parts and collect more information.
We used bandwidth parts to separate UEs in frequency domain and get the same issue (2nd connected UE is on the right hand side):
![screenshot from 2018-12-03 14-10-19](https://user-images.githubusercontent.com/2114618/49383470-1bf3b680-f719-11e8-9cd6-c870bd547dd6.png)

After reconnecting the second UE two times there is no missing subframes anymore:
![no-missed-sf](https://user-images.githubusercontent.com/2114618/49383505-2e6df000-f719-11e8-9a24-a8471eb08eed.png)

We have collected subframes information and results shown that for the 2nd UE every 20th subframe is missing, while for the 1st UE every TTI is allocated. Zero denotes that there were two successive TTI and the value on the Y axis shows the index of the missed subframe (how many successive TTIs were before the missed one).
![missed_sf](https://user-images.githubusercontent.com/2114618/49383966-45f9a880-f71a-11e8-94f6-172bcd3e21ed.png)

Have you noticed this issue before and what could be the reason?

Configuration file:
[enb_remote.conf.zip](https://github.com/srsLTE/srsLTE/files/2640146/enb_remote.conf.zip)

**Comment by kewinrausch** [comment]
I am doing some measurement and testing in a similar situation and just reported an issue. I'm not sure is related somehow with what you have, but with 3 commercial UE I just found out that there was some kind of collision in DCI allocation (or at least is what I isolated right now with testing). 

Take a look to the new issue I [just open](https://github.com/srsLTE/srsLTE/issues/273).

You think that this could be related? Have you checked if you have in the log some trace about the scheduled complaining that is not possible to generate UL/DL DCI?

Cheers,
Kewin R.

**Comment by igorskh** [comment]
> You think that this could be related? Have you checked if you have in the log some trace about the scheduled complaining that is not possible to generate UL/DL DCI?
>

Here is what we got from the logs:
```
10:36:30.135111 [MAC ] [W] [02041] SCHED: Could not schedule DL DCI for rnti=0x47, pid=2, cfi=3
10:36:30.155194 [MAC ] [W] [02061] SCHED: Could not schedule DL DCI for rnti=0x47, pid=2, cfi=3
10:36:30.175113 [MAC ] [W] [02081] SCHED: Could not schedule DL DCI for rnti=0x47, pid=2, cfi=3
10:36:30.195048 [MAC ] [W] [02101] SCHED: Could not schedule DL DCI for rnti=0x47, pid=2, cfi=3
10:36:30.215129 [MAC ] [W] [02121] SCHED: Could not schedule DL DCI for rnti=0x47, pid=2, cfi=3
```
A lot of these messages. When we reconnect the UE and it gets the RNTI 0x48 or 0x49 for example, we do not see this warning so often and do not observe this problem anymore. But I am not yet sure how it can be related to the RNTI as you described in your issue, but we will continue to look into this problem.

**Comment by andrepuschmann** [comment]
Closing issue. Please reopen if it still exists in new release.

**Comment by andrepuschmann** [comment]
I was wrong. The issue hasn't been addressed in new version yet.

**Comment by andrepuschmann** [comment]
Solved in next release. Thanks again for reporting.
