### ISSUE TITLE
Parameters for enb

### ISSUE THREAD

**Issue by QasimBM** [srsLTE/srsLTE#275]
How to set "enbid", cellid, physical cellid, tac? Are they random?

**Comment by SpaceGnome** [comment]
You need to go to the `.srs/` directory and edit the `enb.conf` file

It should look something like this:

`[enb]`
`enb_id = 0x19B`
`cell_id = 0x01`
`phy_cell_id = 1`
`tac = 0x0007`
`mcc = 425`
`mnc = 01`
`mme_addr = 127.0.1.100`
`gtp_bind_addr = 127.0.1.1`
`s1c_bind_addr = 127.0.1.1`
`n_prb = 50`

**Comment by QasimBM** [comment]
I get that. My question was on what bases should I be editing them? What would be my enodeB id, cell id

**Comment by andrepuschmann** [comment]
Not an issue. Closed therefore.
