### ISSUE TITLE
Cell_search cannot change frequency

### ISSUE THREAD

**Issue by xieyaxiongfly** [srsLTE/srsLTE#279]
Dear all,

I got a problem running the cell_search example. 

I am using USRP X310 (I am not sure, whether srsLTE works with X310 or not). 

When I run the cell_search -b 1 - v, I get the error message as follow:

Opening RF device...
[INFO] [UHD] linux; GNU C++ version 7.3.0; Boost_106501; UHD_3.13.0.1-release
Opening USRP with args: type=x300,master_clock_rate=184.32e6
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 1472 bytes.
[INFO] [X300] Radio 1x clock: 184.32 MHz
[INFO] [0/DmaFIFO_0] Initializing block control (NOC ID: 0xF1F0D00000000000)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1299 MB/s)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1300 MB/s)
[INFO] [0/Radio_0] Initializing block control (NOC ID: 0x12AD100000000001)
[INFO] [0/Radio_1] Initializing block control (NOC ID: 0x12AD100000000001)
[INFO] [0/DDC_0] Initializing block control (NOC ID: 0xDDC0000000000000)
[INFO] [0/DDC_1] Initializing block control (NOC ID: 0xDDC0000000000000)
[INFO] [0/DUC_0] Initializing block control (NOC ID: 0xD0C0000000000000)
[INFO] [0/DUC_1] Initializing block control (NOC ID: 0xD0C0000000000000)
nof_freqs: 599
[INFO]: Set rf_freq to 2110.000 MHz
[  0/599]: EARFCN 0 Freq. 2110.00 MHz looking for PSS.

[INFO]: Setting sampling frequency 1.92 MHz for PSS search
[INFO]: Starting receiver...
[INFO]: CP-CFO: estimated=0.066649, mean=0.066649
[INFO]: PSS: id=0, peak_pos=670, peak_value=1.339536
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.214404, mean=0.081424
[INFO]: PSS: id=0, peak_pos=7065, peak_value=1.215625
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.195840, mean=0.092866
[INFO]: PSS: id=0, peak_pos=488, peak_value=1.096967
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.024149, mean=0.081164
[INFO]: PSS: id=0, peak_pos=5851, peak_value=1.312697
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.180149, mean=0.055033
[INFO]: PSS: id=0, peak_pos=5932, peak_value=1.135440
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.059304, mean=0.043599
[INFO]: PSS: id=0, peak_pos=6846, peak_value=1.482998
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.455896, mean=0.084829
[INFO]: PSS: id=0, peak_pos=8074, peak_value=1.089502
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.226347, mean=0.098981
[INFO]: PSS: id=0, peak_pos=8230, peak_value=1.140006
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.127405, mean=0.101823
[INFO]: PSS: id=0, peak_pos=3097, peak_value=1.189355
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.161552, mean=0.107796
[INFO]: PSS: id=0, peak_pos=2662, peak_value=1.014584
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.053675, mean=0.053675
[INFO]: PSS: id=1, peak_pos=8655, peak_value=1.010826
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.154269, mean=0.063734
[INFO]: PSS: id=1, peak_pos=595, peak_value=1.028761
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.381641, mean=0.095525
[INFO]: PSS: id=1, peak_pos=7932, peak_value=1.038318
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.181101, mean=0.104082
[INFO]: PSS: id=1, peak_pos=1918, peak_value=1.067029
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.125147, mean=0.081159
[INFO]: PSS: id=1, peak_pos=2359, peak_value=1.028680
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.054055, mean=0.078449
[INFO]: PSS: id=1, peak_pos=175, peak_value=1.102402
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.058646, mean=0.064740
[INFO]: PSS: id=1, peak_pos=4739, peak_value=1.023709
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.118451, mean=0.070111
[INFO]: PSS: id=1, peak_pos=916, peak_value=1.030938
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.001343, mean=0.062965
[INFO]: PSS: id=1, peak_pos=990, peak_value=1.142080
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.349900, mean=0.091659
[INFO]: PSS: id=1, peak_pos=5444, peak_value=1.373412
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.045570, mean=0.045570
[INFO]: PSS: id=2, peak_pos=736, peak_value=1.048833
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.317738, mean=0.072787
[INFO]: PSS: id=2, peak_pos=6296, peak_value=1.098662
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.055161, mean=0.059992
[INFO]: PSS: id=2, peak_pos=5670, peak_value=1.073278
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.170526, mean=0.071046
[INFO]: PSS: id=2, peak_pos=1137, peak_value=1.015183
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.081135, mean=0.072055
[INFO]: PSS: id=2, peak_pos=423, peak_value=1.411378
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.279837, mean=0.092833
[INFO]: PSS: id=2, peak_pos=4078, peak_value=1.011710
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.317604, mean=0.115310
[INFO]: PSS: id=2, peak_pos=7149, peak_value=1.023484
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.446092, mean=0.059170
[INFO]: PSS: id=2, peak_pos=3303, peak_value=1.071922
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.340113, mean=0.087264
[INFO]: PSS: id=2, peak_pos=1368, peak_value=1.096769
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.189067, mean=0.097444
[INFO]: PSS: id=2, peak_pos=5743, peak_value=1.120156
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: Set rf_freq to 2110.100 MHz
[  1/599]: EARFCN 1 Freq. 2110.10 MHz looking for PSS.

[INFO]: Setting sampling frequency 1.92 MHz for PSS search
[INFO]: Starting receiver...
Error timed out while receiving samples from UHD.
Error receiving samples
Error calling srslte_ue_sync_work()
Error searching cell
Error searching cell

The problem is that when the program start to scan the second frequency (2110.10MHz), the USRP report a time out error. 

Therefore, I tried another command “ ./cell_search -b 1 -s 1 -e 3 -v”, and I get the following error message:

Opening RF device...
[INFO] [UHD] linux; GNU C++ version 7.3.0; Boost_106501; UHD_3.13.0.1-release
Opening USRP with args: type=x300,master_clock_rate=184.32e6
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 1472 bytes.
[INFO] [X300] Radio 1x clock: 184.32 MHz
[INFO] [0/DmaFIFO_0] Initializing block control (NOC ID: 0xF1F0D00000000000)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1318 MB/s)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1309 MB/s)
[INFO] [0/Radio_0] Initializing block control (NOC ID: 0x12AD100000000001)
[INFO] [0/Radio_1] Initializing block control (NOC ID: 0x12AD100000000001)
[INFO] [0/DDC_0] Initializing block control (NOC ID: 0xDDC0000000000000)
[INFO] [0/DDC_1] Initializing block control (NOC ID: 0xDDC0000000000000)
[INFO] [0/DUC_0] Initializing block control (NOC ID: 0xD0C0000000000000)
[INFO] [0/DUC_1] Initializing block control (NOC ID: 0xD0C0000000000000)
nof_freqs: 2
[INFO]: Set rf_freq to 2110.100 MHz
[  0/2]: EARFCN 1 Freq. 2110.10 MHz looking for PSS.

[INFO]: Setting sampling frequency 1.92 MHz for PSS search
[INFO]: Starting receiver...
[INFO]: CP-CFO: estimated=0.064905, mean=0.064905
[INFO]: PSS: id=0, peak_pos=3890, peak_value=1.181932
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.036249, mean=0.062040
[INFO]: PSS: id=0, peak_pos=5145, peak_value=1.057476
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.043232, mean=0.060159
[INFO]: PSS: id=0, peak_pos=517, peak_value=1.060595
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.020756, mean=0.052067
[INFO]: PSS: id=0, peak_pos=8709, peak_value=1.244484
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.004572, mean=0.047318
[INFO]: PSS: id=0, peak_pos=1241, peak_value=1.052639
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.022534, mean=0.044840
[INFO]: PSS: id=0, peak_pos=3119, peak_value=1.045657
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.005619, mean=0.040917
[INFO]: PSS: id=0, peak_pos=8312, peak_value=1.022651
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.008100, mean=0.036016
[INFO]: PSS: id=0, peak_pos=1941, peak_value=1.235738
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.010807, mean=0.031333
[INFO]: PSS: id=0, peak_pos=8996, peak_value=1.006491
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.024870, mean=0.030687
[INFO]: PSS: id=0, peak_pos=4947, peak_value=1.025244
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.036512, mean=0.036512
[INFO]: PSS: id=1, peak_pos=5567, peak_value=1.099462
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.015905, mean=0.031270
[INFO]: PSS: id=1, peak_pos=6000, peak_value=1.089841
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.024611, mean=0.030604
[INFO]: PSS: id=1, peak_pos=2873, peak_value=1.012491
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.037536, mean=0.031298
[INFO]: PSS: id=1, peak_pos=7978, peak_value=1.049249
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.011309, mean=0.029299
[INFO]: PSS: id=1, peak_pos=9206, peak_value=1.030742
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.029709, mean=0.029340
[INFO]: PSS: id=1, peak_pos=4000, peak_value=1.080926
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.075812, mean=0.033987
[INFO]: PSS: id=1, peak_pos=5327, peak_value=1.089457
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.006949, mean=0.029893
[INFO]: PSS: id=1, peak_pos=2744, peak_value=1.016759
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.007208, mean=0.026183
[INFO]: PSS: id=1, peak_pos=5009, peak_value=1.008556
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.005778, mean=0.022987
[INFO]: PSS: id=1, peak_pos=5467, peak_value=1.483459
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.011447, mean=0.011447
[INFO]: PSS: id=2, peak_pos=8335, peak_value=1.265054
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.033446, mean=0.013647
[INFO]: PSS: id=2, peak_pos=4190, peak_value=1.150658
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.121587, mean=0.024441
[INFO]: PSS: id=2, peak_pos=1004, peak_value=1.021036
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.032223, mean=0.025219
[INFO]: PSS: id=2, peak_pos=1791, peak_value=1.156843
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.027688, mean=0.025466
[INFO]: PSS: id=2, peak_pos=699, peak_value=1.336000
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.007717, mean=0.023691
[INFO]: PSS: id=2, peak_pos=8170, peak_value=1.288307
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=-0.000036, mean=0.021318
[INFO]: PSS: id=2, peak_pos=9160, peak_value=1.038788
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.063659, mean=0.025552
[INFO]: PSS: id=2, peak_pos=3806, peak_value=1.101132
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.012675, mean=0.024265
[INFO]: PSS: id=2, peak_pos=6016, peak_value=1.101061
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: CP-CFO: estimated=0.018485, mean=0.023687
[INFO]: PSS: id=2, peak_pos=8765, peak_value=1.090525
[INFO]: SYNC FIND: sf_idx=0, ret=0, next_state=0
[INFO]: Set rf_freq to 2110.200 MHz
[  1/2]: EARFCN 2 Freq. 2110.20 MHz looking for PSS.

[INFO]: Setting sampling frequency 1.92 MHz for PSS search
[INFO]: Starting receiver...
Error timed out while receiving samples from UHD.
Error receiving samples
Error calling srslte_ue_sync_work()
Error searching cell
Error searching cell

From the message, I found that the it is not about the 2110.20MHz frequency. The cell search just cannot loop. If the program reconfigure the center frequency, the USRP cannot work and collect the IQ data. 

Can anyone kindly help me with this problem?

Thanks in advance.

**Comment by andrepuschmann** [comment]
Doesn't look like a srsLTE error. Rather UHD or USRP in general. Please check if your daugtherboard supports that band at all.

**Comment by xieyaxiongfly** [comment]
Thanks for your advice. I have checked my hardware. The daughterboard (UBX160) I am using supports 10MHz-6GHz frequency band. 

Can I ask a few more questions?

1, can srsLTE works with USRP X310? 

2, As you can see that I can search the first frequency, but fails when switching to the next frequency. Is there any possible reason that will cause such a problem?

**Comment by xieyaxiongfly** [comment]
I also tried multiple different USRP X310. I got the same error messages.

**Comment by xieyaxiongfly** [comment]
I also tried  "./pdsch_ue -f 1800e6" which searches for the cell at the frequency of 1.8GHz repeatly, I got the following message: 


Opening RF device with 1 RX antennas...
[INFO] [UHD] linux; GNU C++ version 7.3.0; Boost_106501; UHD_3.13.0.1-release
Opening USRP with args: type=x300,master_clock_rate=184.32e6
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 1472 bytes.
[INFO] [X300] Radio 1x clock: 184.32 MHz
[INFO] [0/DmaFIFO_0] Initializing block control (NOC ID: 0xF1F0D00000000000)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1305 MB/s)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1320 MB/s)
[INFO] [0/Radio_0] Initializing block control (NOC ID: 0x12AD100000000001)
[INFO] [0/Radio_1] Initializing block control (NOC ID: 0x12AD100000000001)
[INFO] [0/DDC_0] Initializing block control (NOC ID: 0xDDC0000000000000)
[INFO] [0/DDC_1] Initializing block control (NOC ID: 0xDDC0000000000000)
[INFO] [0/DUC_0] Initializing block control (NOC ID: 0xD0C0000000000000)
[INFO] [0/DUC_1] Initializing block control (NOC ID: 0xD0C0000000000000)
Starting AGC thread...
Tunning receiver to 1800.000 MHz
Searching for cell...
Could not find any cell in this frequency
Cell not found after 0 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 1 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 2 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 3 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 4 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 5 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 6 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 7 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 8 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 9 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 10 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Could not find any cell in this frequency
Cell not found after 11 trials. Trying again (Press Ctrl+C to exit)
Searching for cell...
Error timed out while receiving samples from UHD.
Error receiving samples
Error calling srslte_ue_sync_work()
Error searching cell
Error searching cell
Error searching for cell

I repeat the above process multiple times and found that the error appears after a random number of trials (in the above example, it is 11 trials). 

I feel that the code has some problem when running on X310 USRP hardware. 

Could you kindly provide some advices for it? Is chaning the hardware the only solution for it?

**Comment by andrepuschmann** [comment]
We've the X310 running in many setups. Note that it usually requires different power levels than, for example, the B210. Also, we're running on UHD 3.9.7 LTS.

**Comment by igorskh** [comment]
We use USRP X310 for srsLTE UE and eNB without any problems with UHD 3.10, it runs stable for hours.

There are might be several issues, but it doesn't seem to be related to srsLTE:
1. Try to run with a lower version of UHD (3.9/3.10).
2. Check the connection from the PC to the USRP.
3. Might a performance issue of the PC itself (low performance in general, other processes running).
4. At least with the version of UHD we use the application should be run as root e.g. `sudo ./pdsch_ue -f 1800e6`.

**Comment by xieyaxiongfly** [comment]
I change the UHD to 3.9 and it works!! 

Thanks for your advice. It really helps a lot!
