### ISSUE TITLE
translate asn to c code

### ISSUE THREAD

**Issue by maxbeyond** [srsLTE/srsLTE#281]
I am wondering how the asn has been translated to c code like the file 'liblte_s1ap.cc' and 'liblte_s1ap.h'. Because I want to add a X2 interface and I am supposed to translate asn related to X2.

**Comment by ismagom** [comment]
Not an issue. Thanks

**Comment by frankist** [comment]
Hey,

The code was manually written. Maybe in the future, we will design an
automatic generator for the s1ap.

Regards,
Francisco
