### ISSUE TITLE
Potential bug in liblte_s1ap_pack_subscriberprofileidforrfp()

### ISSUE THREAD

**Issue by Acciente717** [srsLTE/srsLTE#282]
In the function in `liblte_s1ap.cc`
```c++
LIBLTE_ERROR_ENUM liblte_x2ap_pack_subscribeprofileidforrfp(
LIBLTE_X2AP_SUBSCRIBERPROFILEIDFORRFP_STRUCT                            *ie,
uint8_t                                                                 **ptr)
```
The lower and upper bound for `SubscriberProfileIDforRFP` should be 1 and 256, respectively, according to specification written in ASN.1. However, `uint8_t` is uncapable for storing 256, which will overflow to zero, and might lead to subtle error.

**Comment by andrepuschmann** [comment]
Thanks for that. We'll look into it.
