### ISSUE TITLE
something wrong with function liblte_rrc_pack_quantity_config_ie(

### ISSUE THREAD

**Issue by sunshaozong111** [srsLTE/srsLTE#283]
I find that this function is incomplete. The question is as follows,which may cause a disaster that eNodeB cannot pack measurement configurations correctly.

       // Quality Config EUTRA
        if(qc->qc_eutra_present)
        {
            liblte_rrc_pack_filter_coefficient_ie(qc->qc_eutra.fc_rsrp, ie_ptr);
            liblte_rrc_pack_filter_coefficient_ie(qc->qc_eutra.fc_rsrq, ie_ptr);
        }

Here is my modification.

     if(qc->qc_eutra_present)
          {
            liblte_value_2_bits(qc->qc_eutra.fc_rsrp_not_default, ie_ptr, 1);
            liblte_value_2_bits(qc->qc_eutra.fc_rsrq_not_default, ie_ptr, 1);
            liblte_rrc_pack_filter_coefficient_ie(qc->qc_eutra.fc_rsrp, ie_ptr);
            liblte_rrc_pack_filter_coefficient_ie(qc->qc_eutra.fc_rsrq, ie_ptr);
        }
Welcome to correct me if I submit a wrong modification .

**Comment by andrepuschmann** [comment]
Closing it as newer releases use other RRC library.
