### ISSUE TITLE
BladeRF x115 limesdr

### ISSUE THREAD

**Issue by Keskebeu** [srsLTE/srsLTE#289]
It says here that srslte has been tested with BladeRF and limesdr. But it works only with ettus b200 b210. I have tried both ue and enb working with b200. Any updates of is it supposed to woork with limesdr soon? At least in one end?

**Comment by andrepuschmann** [comment]
We have it working but, I've to admit, it's a bit wobbly. Most likely it's gain tuning for both rx and tx that cause issues. Start using pdsch_ue and pdsch_enodeb and fine tune those before going the srsUE and srsENB.
