### ISSUE TITLE
how to log

### ISSUE THREAD

**Issue by manang** [srsLTE/srsLTE#295]
Hi,
i'm trying to use the internal logger of srsLTE.
For example, in pdcp_entity.cc, in add_bearer I'm using log->info("string test");
where can I see the output?
I don' see anything on screen.
thank you very much.

Angelo

**Comment by andrepuschmann** [comment]
In the log file if the pdpc log level is at least info.

**Comment by manang** [comment]
where is the log file?
Thank you very much

**Comment by andrepuschmann** [comment]
Usually in /tmp/ue.log if you've not changed this. But this is not a code issue, so please use the list for that.
