### ISSUE TITLE
ASN1: octstring_to_number and number_to_octstring use wrong endianess

### ISSUE THREAD

**Issue by JGRennison** [srsLTE/srsLTE#297]
The methods `octstring_to_number` and `number_to_octstring` added in 0204db2e12b67d7e9335ded313dea5a5940b1843 incorrectly use little-endian order for multi-octet fields (where the least significant byte is first and the most significant byte is last, which is the wrong order).

The ASN1 PER spec and the methods `octstring_to_string` and `string_to_octstring` use big-endian order (where the most significant byte is first and the least significant byte is last).

As an example this causes the field tmgi_r9_s::service_id_r9 to be extracted incorrectly by the UE when using to_number(), but correctly when using to_string().

**Comment by andrepuschmann** [comment]
Thanks for reporting that. We've fixed that and it made into the final 18.12 which has just been pushed and tagged.
