### ISSUE TITLE
pmch_file_test Fails with USE_LTE_RATES Enabled

### ISSUE THREAD

**Issue by sramlall** [srsLTE/srsLTE#313]
## Issue Description ##
When I compile srsLTE without changing any options, all tests pass when running make test.  However, pmch_file_test fails when I run make test after compiling with the USE_LTE_RATES CMake option turned on in CMakeLists.txt.

## Setup Details ##
Ubuntu 16.04.5 LTS 64-bit
USRP B205mini and B210
Only change to files I made before compiling was enabling the USE_LTE_RATES CMake option in CMakeLists.txt.

## Expected Behavior ##
All tests using make test should pass.

## Actual Behaviour ##
pmch_file_test fails.

## Steps to reproduce the problem ##
Just change the USE_LTE_RATES option from OFF to ON in CMakeLists.txt

**Comment by andrepuschmann** [comment]
Will be fixed with the new release.
