### ISSUE TITLE
Ubuntu ppa is broken

### ISSUE THREAD

**Issue by osmoc** [srsLTE/srsLTE#315]
## Issue Description ##
srsLTE PPA is unusable:
```
E: The repository 'http://ppa.launchpad.net/srslte/releases/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
## Setup Details ##
```
sudo add-apt-repository ppa:srslte/releases
sudo apt update
```

## Expected Behavior ##
Smooth update.

## Actual Behaviour ##
See above.

## Steps to reproduce the problem ##
See above.

## Additional Information ##
None.

**Comment by suttonpd** [comment]
Thanks for flagging this - we are now creating packages for cosmic and disco in addition to bionic.
