### ISSUE TITLE
Mod2 not considered in the output sequence for scrambling

### ISSUE THREAD

**Issue by eshikafe** [srsLTE/srsLTE#317]
According to 3GPP TS 36.211 section 7.2, the output sequence c(n) = (x1[n+Nc] + x2[n+Nc]) mod2

In line number 80 of sequence.c, I noticed that the mod2 of the addition is not computed:
https://github.com/srsLTE/srsLTE/blob/30834968b240c29b8ac90b38558eaca4f487044c/lib/src/phy/common/sequence.c#L80

Any reason for this? Thanks

**Comment by xavierarteaga** [comment]
Since the mod2 operation is for taking the lowest significant bit from the addition. It is equivalent to an AND 1. More information: https://www.geeksforgeeks.org/compute-modulus-division-by-a-power-of-2-number/

**Comment by eshikafe** [comment]
Cool. I am used to the xor equivalent.
