### ISSUE TITLE
problem during sudo srslte_install_configs.sh service

### ISSUE THREAD

**Issue by jbdu94** [srsLTE/srsLTE#320]
Hi

I have a problem during `sudo srslte_install_configs.sh service
Installing srsLTE configuration files:
 - Creating srsLTE config folder /etc/srslte
 - /usr/local/share/srslte/ue.conf.example doesn't exists. Skipping it.
 - /usr/local/share/srslte/enb.conf.example doesn't exists. Skipping it.
 - /usr/local/share/srslte/sib.conf.example doesn't exists. Skipping it.
 - /usr/local/share/srslte/rr.conf.example doesn't exists. Skipping it.
 - /usr/local/share/srslte/drb.conf.example doesn't exists. Skipping it.
 - Installing epc.conf.example in /etc/srslte/epc.conf
 - Installing mbms.conf.example in /etc/srslte/mbms.conf
 - Installing user_db.csv.example in /etc/srslte/user_db.csv
`
And when I launch srsenb, it says:
`bash: srsenb: command not found`
I have HackRF, will it work ?

Please help, I have followed instructions on your page and I have a Kali linux updated.
Thanks in advance

**Comment by andrepuschmann** [comment]
Just means that you've not compiled srsenb/srsue because no compatible RF front end was found. We don't support the HackRF. Not that it is half-duplex only.
