### ISSUE TITLE
Can srsLTE library called in c++ program?

### ISSUE THREAD

**Issue by YaxiongXiePrinceton** [srsLTE/srsLTE#324]
Before filing an issue, search for solutions here:
- srsLTE users mailing list (http://www.softwareradiosystems.com/mailman/listinfo/srslte-users)

## Issue Description ##
[Describe the issue in detail]
Dear all,

I want to call a lot of srsLTE phy layer functions in a c++ program. Can I ask whether the srslte library can be called in a C++ program? Do I need to write a wrapper for the C++ program?

Thanks in advance.
## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by ismagom** [comment]
Not an issue
