### ISSUE TITLE
Make failed, rf_zmq_imp.c:177:40

### ISSUE THREAD

**Issue by jonah01** [srsLTE/srsLTE#352]
Hi,
i want to install srsLTE on an ubuntu 16.04 System, but the make process failed. I had searched for an issue like that, but i didn't find something like that.

I don't know what to do, maybe someone can give me a solution.
Best regards
jonah

Here is the message of the terminal:

after cmake ../

ubuntu@ubuntu-ThinkPad-T550:~/srsLTE/build$ make
Scanning dependencies of target rrc_asn1
[  0%] Building CXX object lib/src/asn1/CMakeFiles/rrc_asn1.dir/rrc_asn1.cc.o
[  1%] Building CXX object lib/src/asn1/CMakeFiles/rrc_asn1.dir/rrc_asn1_enum.cc.o
[  1%] Building CXX object lib/src/asn1/CMakeFiles/rrc_asn1.dir/asn1_utils.cc.o
[  1%] Linking CXX static library librrc_asn1.a
[  1%] Built target rrc_asn1
Scanning dependencies of target srslte_asn1
[  1%] Building CXX object lib/src/asn1/CMakeFiles/srslte_asn1.dir/liblte_common.cc.o
[  1%] Building CXX object lib/src/asn1/CMakeFiles/srslte_asn1.dir/liblte_mme.cc.o
[  2%] Building CXX object lib/src/asn1/CMakeFiles/srslte_asn1.dir/liblte_s1ap.cc.o
[  2%] Building CXX object lib/src/asn1/CMakeFiles/srslte_asn1.dir/liblte_m2ap.cc.o
[  2%] Building CXX object lib/src/asn1/CMakeFiles/srslte_asn1.dir/gtpc.cc.o
[  2%] Linking CXX static library libsrslte_asn1.a
[  2%] Built target srslte_asn1
Scanning dependencies of target gen_build_info
-- Generating build_info.h
[  2%] Built target gen_build_info
Scanning dependencies of target srslte_common
[  3%] Building C object lib/src/common/CMakeFiles/srslte_common.dir/threads.c.o
[  3%] Building C object lib/src/common/CMakeFiles/srslte_common.dir/gen_mch_tables.c.o
[  3%] Building C object lib/src/common/CMakeFiles/srslte_common.dir/version.c.o
[  3%] Building C object lib/src/common/CMakeFiles/srslte_common.dir/crash_handler.c.o
[  4%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/task_dispatcher.cc.o
[  4%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/s1ap_pcap.cc.o
[  4%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/pdu_queue.cc.o
[  4%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/thread_pool.cc.o
[  5%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/snow_3g.cc.o
[  5%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/logger_file.cc.o
[  5%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/buffer_pool.cc.o
[  5%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/tti_sync_cv.cc.o
[  6%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/security.cc.o
[  6%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/pdu.cc.o
[  6%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/log_filter.cc.o
[  6%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/nas_pcap.cc.o
[  7%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/rlc_pcap.cc.o
[  7%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/mac_pcap.cc.o
[  7%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/liblte_security.cc.o
[  7%] Building CXX object lib/src/common/CMakeFiles/srslte_common.dir/arch_select.cc.o
[  8%] Linking CXX static library libsrslte_common.a
[  8%] Built target srslte_common
Scanning dependencies of target arch_select
[  8%] Building CXX object lib/src/common/CMakeFiles/arch_select.dir/arch_select.cc.o
[  9%] Linking CXX executable arch_select
[  9%] Built target arch_select
Scanning dependencies of target srslte_enb
[ 10%] Building C object lib/src/phy/enb/CMakeFiles/srslte_enb.dir/enb_ul.c.o
[ 10%] Building C object lib/src/phy/enb/CMakeFiles/srslte_enb.dir/enb_dl.c.o
[ 10%] Built target srslte_enb
Scanning dependencies of target srslte_agc
[ 10%] Building C object lib/src/phy/agc/CMakeFiles/srslte_agc.dir/agc.c.o
[ 10%] Built target srslte_agc
Scanning dependencies of target srslte_ch_estimation
[ 11%] Building C object lib/src/phy/ch_estimation/CMakeFiles/srslte_ch_estimation.dir/refsignal_ul.c.o
[ 11%] Building C object lib/src/phy/ch_estimation/CMakeFiles/srslte_ch_estimation.dir/chest_dl.c.o
[ 11%] Building C object lib/src/phy/ch_estimation/CMakeFiles/srslte_ch_estimation.dir/refsignal_dl.c.o
[ 11%] Building C object lib/src/phy/ch_estimation/CMakeFiles/srslte_ch_estimation.dir/chest_ul.c.o
[ 12%] Building C object lib/src/phy/ch_estimation/CMakeFiles/srslte_ch_estimation.dir/chest_common.c.o
[ 12%] Built target srslte_ch_estimation
Scanning dependencies of target srslte_phy_common
[ 12%] Building C object lib/src/phy/common/CMakeFiles/srslte_phy_common.dir/phy_common.c.o
[ 12%] Building C object lib/src/phy/common/CMakeFiles/srslte_phy_common.dir/timestamp.c.o
[ 13%] Building C object lib/src/phy/common/CMakeFiles/srslte_phy_common.dir/sequence.c.o
[ 13%] Built target srslte_phy_common
Scanning dependencies of target srslte_fec
[ 13%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/viterbi37_avx2.c.o
[ 13%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/turbodecoder.c.o
[ 14%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/tc_interl_lte.c.o
[ 14%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/softbuffer.c.o
[ 14%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/viterbi.c.o
[ 14%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/rm_turbo.c.o
[ 15%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/viterbi37_avx2_16bit.c.o
[ 15%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/crc.c.o
[ 15%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/parity.c.o
[ 15%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/tc_interl_umts.c.o
[ 16%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/turbocoder.c.o
[ 16%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/rm_conv.c.o
[ 16%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/viterbi37_sse.c.o
[ 16%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/convcoder.c.o
[ 17%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/turbodecoder_sse.c.o
[ 17%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/viterbi37_port.c.o
[ 17%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/turbodecoder_gen.c.o
[ 17%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/cbsegm.c.o
[ 18%] Building C object lib/src/phy/fec/CMakeFiles/srslte_fec.dir/viterbi37_neon.c.o
[ 18%] Built target srslte_fec
Scanning dependencies of target srslte_mimo
[ 18%] Building C object lib/src/phy/mimo/CMakeFiles/srslte_mimo.dir/precoding.c.o
[ 18%] Building C object lib/src/phy/mimo/CMakeFiles/srslte_mimo.dir/layermap.c.o
[ 18%] Built target srslte_mimo
Scanning dependencies of target srslte_phch
[ 18%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/pucch.c.o
[ 18%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/pmch.c.o
[ 19%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/phich.c.o
[ 19%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/cqi.c.o
[ 19%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/prach.c.o
[ 19%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/prb_dl.c.o
[ 20%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/uci.c.o
[ 20%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/sequences.c.o
[ 20%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/pcfich.c.o
[ 20%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/regs.c.o
[ 21%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/sch.c.o
[ 21%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/pbch.c.o
[ 21%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/pusch.c.o
[ 21%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/ra.c.o
[ 22%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/pdsch.c.o
[ 22%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/ra_dl.c.o
[ 22%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/ra_ul.c.o
[ 22%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/pdcch.c.o
[ 23%] Building C object lib/src/phy/phch/CMakeFiles/srslte_phch.dir/dci.c.o
[ 23%] Built target srslte_phch
Scanning dependencies of target srslte_sync
[ 23%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/cfo.c.o
[ 23%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/sfo.c.o
[ 23%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/find_sss.c.o
[ 24%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/sss.c.o
[ 24%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/cp.c.o
[ 24%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/sync.c.o
[ 24%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/gen_sss.c.o
[ 25%] Building C object lib/src/phy/sync/CMakeFiles/srslte_sync.dir/pss.c.o
[ 25%] Built target srslte_sync
Scanning dependencies of target srslte_utils
[ 25%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/ringbuffer.c.o
[ 25%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/phy_logger.c.o
[ 26%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/debug.c.o
[ 26%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/cexptab.c.o
[ 26%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/vector_simd.c.o
[ 26%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/vector.c.o
[ 27%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/mat.c.o
[ 27%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/convolution.c.o
[ 27%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/bit.c.o
[ 27%] Building C object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/filter.c.o
[ 28%] Building CXX object lib/src/phy/utils/CMakeFiles/srslte_utils.dir/random.cpp.o
[ 28%] Built target srslte_utils
Scanning dependencies of target srslte_channel
[ 28%] Building C object lib/src/phy/channel/CMakeFiles/srslte_channel.dir/ch_awgn.c.o
[ 28%] Building C object lib/src/phy/channel/CMakeFiles/srslte_channel.dir/fading.c.o
[ 28%] Building C object lib/src/phy/channel/CMakeFiles/srslte_channel.dir/gauss.c.o
[ 28%] Built target srslte_channel
Scanning dependencies of target srslte_dft
[ 28%] Building C object lib/src/phy/dft/CMakeFiles/srslte_dft.dir/dft_fftw.c.o
[ 28%] Building C object lib/src/phy/dft/CMakeFiles/srslte_dft.dir/dft_precoding.c.o
[ 28%] Building C object lib/src/phy/dft/CMakeFiles/srslte_dft.dir/ofdm.c.o
[ 28%] Built target srslte_dft
Scanning dependencies of target srslte_io
[ 28%] Building C object lib/src/phy/io/CMakeFiles/srslte_io.dir/filesink.c.o
[ 28%] Building C object lib/src/phy/io/CMakeFiles/srslte_io.dir/filesource.c.o
[ 28%] Building C object lib/src/phy/io/CMakeFiles/srslte_io.dir/binsource.c.o
[ 29%] Building C object lib/src/phy/io/CMakeFiles/srslte_io.dir/netsink.c.o
[ 29%] Building C object lib/src/phy/io/CMakeFiles/srslte_io.dir/netsource.c.o
[ 29%] Built target srslte_io
Scanning dependencies of target srslte_modem
[ 30%] Building C object lib/src/phy/modem/CMakeFiles/srslte_modem.dir/demod_hard.c.o
[ 30%] Building C object lib/src/phy/modem/CMakeFiles/srslte_modem.dir/demod_soft.c.o
[ 30%] Building C object lib/src/phy/modem/CMakeFiles/srslte_modem.dir/hard_demod_lte.c.o
[ 30%] Building C object lib/src/phy/modem/CMakeFiles/srslte_modem.dir/mod.c.o
[ 31%] Building C object lib/src/phy/modem/CMakeFiles/srslte_modem.dir/modem_table.c.o
[ 31%] Building C object lib/src/phy/modem/CMakeFiles/srslte_modem.dir/lte_tables.c.o
[ 31%] Built target srslte_modem
Scanning dependencies of target srslte_resampling
[ 31%] Building C object lib/src/phy/resampling/CMakeFiles/srslte_resampling.dir/decim.c.o
[ 31%] Building C object lib/src/phy/resampling/CMakeFiles/srslte_resampling.dir/interp.c.o
[ 31%] Building C object lib/src/phy/resampling/CMakeFiles/srslte_resampling.dir/resample_arb.c.o
[ 31%] Built target srslte_resampling
Scanning dependencies of target srslte_scrambling
[ 32%] Building C object lib/src/phy/scrambling/CMakeFiles/srslte_scrambling.dir/scrambling.c.o
[ 32%] Built target srslte_scrambling
Scanning dependencies of target srslte_ue
[ 32%] Building C object lib/src/phy/ue/CMakeFiles/srslte_ue.dir/ue_sync.c.o
[ 32%] Building C object lib/src/phy/ue/CMakeFiles/srslte_ue.dir/ue_ul.c.o
[ 32%] Building C object lib/src/phy/ue/CMakeFiles/srslte_ue.dir/ue_cell_search.c.o
[ 33%] Building C object lib/src/phy/ue/CMakeFiles/srslte_ue.dir/ue_mib.c.o
[ 33%] Building C object lib/src/phy/ue/CMakeFiles/srslte_ue.dir/ue_dl.c.o
[ 33%] Built target srslte_ue
Scanning dependencies of target srslte_phy
[ 33%] Linking CXX static library libsrslte_phy.a
[ 33%] Built target srslte_phy
Scanning dependencies of target refsignal_ul_test_all
[ 33%] Building C object lib/src/phy/ch_estimation/test/CMakeFiles/refsignal_ul_test_all.dir/refsignal_ul_test.c.o
[ 34%] Linking CXX executable refsignal_ul_test_all
[ 34%] Built target refsignal_ul_test_all
Scanning dependencies of target chest_test_ul
[ 34%] Building C object lib/src/phy/ch_estimation/test/CMakeFiles/chest_test_ul.dir/chest_test_ul.c.o
[ 35%] Linking CXX executable chest_test_ul
[ 35%] Built target chest_test_ul
Scanning dependencies of target chest_test_dl
[ 35%] Building C object lib/src/phy/ch_estimation/test/CMakeFiles/chest_test_dl.dir/chest_test_dl.c.o
[ 35%] Linking CXX executable chest_test_dl
[ 35%] Built target chest_test_dl
Scanning dependencies of target rm_turbo_test
[ 35%] Building C object lib/src/phy/fec/test/CMakeFiles/rm_turbo_test.dir/rm_turbo_test.c.o
[ 35%] Linking CXX executable rm_turbo_test
[ 35%] Built target rm_turbo_test
Scanning dependencies of target turbocoder_test
[ 36%] Building C object lib/src/phy/fec/test/CMakeFiles/turbocoder_test.dir/turbocoder_test.c.o
[ 36%] Linking CXX executable turbocoder_test
[ 36%] Built target turbocoder_test
Scanning dependencies of target rm_conv_test
[ 36%] Building C object lib/src/phy/fec/test/CMakeFiles/rm_conv_test.dir/rm_conv_test.c.o
[ 37%] Linking CXX executable rm_conv_test
[ 37%] Built target rm_conv_test
Scanning dependencies of target viterbi_test
[ 37%] Building C object lib/src/phy/fec/test/CMakeFiles/viterbi_test.dir/viterbi_test.c.o
[ 38%] Linking CXX executable viterbi_test
[ 38%] Built target viterbi_test
Scanning dependencies of target crc_test
[ 38%] Building C object lib/src/phy/fec/test/CMakeFiles/crc_test.dir/crc_test.c.o
[ 38%] Linking CXX executable crc_test
[ 38%] Built target crc_test
Scanning dependencies of target turbodecoder_test
[ 38%] Building C object lib/src/phy/fec/test/CMakeFiles/turbodecoder_test.dir/turbodecoder_test.c.o
[ 38%] Linking CXX executable turbodecoder_test
[ 38%] Built target turbodecoder_test
Scanning dependencies of target pmi_select_test
[ 38%] Building C object lib/src/phy/mimo/test/CMakeFiles/pmi_select_test.dir/pmi_select_test.c.o
[ 38%] Linking CXX executable pmi_select_test
[ 38%] Built target pmi_select_test
Scanning dependencies of target layermap_test
[ 38%] Building C object lib/src/phy/mimo/test/CMakeFiles/layermap_test.dir/layermap_test.c.o
[ 39%] Linking CXX executable layermap_test
[ 39%] Built target layermap_test
Scanning dependencies of target precoding_test
[ 39%] Building C object lib/src/phy/mimo/test/CMakeFiles/precoding_test.dir/precoder_test.c.o
[ 39%] Linking CXX executable precoding_test
[ 39%] Built target precoding_test
Scanning dependencies of target pdsch_test
[ 39%] Building C object lib/src/phy/phch/test/CMakeFiles/pdsch_test.dir/pdsch_test.c.o
[ 39%] Linking CXX executable pdsch_test
[ 39%] Built target pdsch_test
Scanning dependencies of target srslte_rf_utils
[ 39%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf_utils.dir/rf_utils.c.o
[ 39%] Linking CXX static library libsrslte_rf_utils.a
[ 39%] Built target srslte_rf_utils
Scanning dependencies of target srslte_rf
[ 40%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_imp.c.o
[ 40%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_uhd_imp.c.o
[ 40%] Building CXX object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/uhd_c_api.cpp.o
[ 40%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_blade_imp.c.o
[ 41%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_zmq_imp.c.o
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c: In function ‘rf_zmq_tx’:
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:177:40: error: passing argument 2 of ‘zmq_recv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     n = zmq_recv(handler->transmitter, &dummy, sizeof(dummy), 0);
                                        ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:230:16: note: expected ‘zmq_msg_t * {aka struct <anonymous> *}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 ZMQ_EXPORT int zmq_recv (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:177:9: error: too many arguments to function ‘zmq_recv’
     n = zmq_recv(handler->transmitter, &dummy, sizeof(dummy), 0);
         ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:230:16: note: declared here
 ZMQ_EXPORT int zmq_recv (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:191:40: error: passing argument 2 of ‘zmq_send’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     n = zmq_send(handler->transmitter, buffer, nbytes, 0);
                                        ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:229:16: note: expected ‘zmq_msg_t * {aka struct <anonymous> *}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 ZMQ_EXPORT int zmq_send (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:191:9: error: too many arguments to function ‘zmq_send’
     n = zmq_send(handler->transmitter, buffer, nbytes, 0);
         ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:229:16: note: declared here
 ZMQ_EXPORT int zmq_send (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c: In function ‘rf_zmq_async_rx_thread’:
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:243:39: error: passing argument 2 of ‘zmq_send’ from incompatible pointer type [-Werror=incompatible-pointer-types]
       n = zmq_send(handler->receiver, &dummy, sizeof(dummy), 0);
                                       ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:229:16: note: expected ‘zmq_msg_t * {aka struct <anonymous> *}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 ZMQ_EXPORT int zmq_send (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:243:11: error: too many arguments to function ‘zmq_send’
       n = zmq_send(handler->receiver, &dummy, sizeof(dummy), 0);
           ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:229:16: note: declared here
 ZMQ_EXPORT int zmq_send (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:253:39: error: passing argument 2 of ‘zmq_recv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
       n = zmq_recv(handler->receiver, handler->buffer_rx, BUFFER_SIZE, 0);
                                       ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:230:16: note: expected ‘zmq_msg_t * {aka struct <anonymous> *}’ but argument is of type ‘_Complex float *’
 ZMQ_EXPORT int zmq_recv (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:253:11: error: too many arguments to function ‘zmq_recv’
       n = zmq_recv(handler->receiver, handler->buffer_rx, BUFFER_SIZE, 0);
           ^
In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
/usr/include/zmq.h:230:16: note: declared here
 ZMQ_EXPORT int zmq_recv (void *s, zmq_msg_t *msg, int flags);
                ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c: In function ‘rf_zmq_open_multi’:
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:427:24: warning: implicit declaration of function ‘zmq_ctx_new’ [-Wimplicit-function-declaration]
     handler->context = zmq_ctx_new();
                        ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:427:22: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     handler->context = zmq_ctx_new();
                      ^
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c: In function ‘rf_zmq_close’:
/home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:580:5: warning: implicit declaration of function ‘zmq_ctx_destroy’ [-Wimplicit-function-declaration]
     zmq_ctx_destroy(handler->context);
     ^
cc1: some warnings being treated as errors
lib/src/phy/rf/CMakeFiles/srslte_rf.dir/build.make:158: die Regel für Ziel „lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_zmq_imp.c.o“ scheiterte
make[2]: *** [lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_zmq_imp.c.o] Fehler 1
CMakeFiles/Makefile2:2985: die Regel für Ziel „lib/src/phy/rf/CMakeFiles/srslte_rf.dir/all“ scheiterte
make[1]: *** [lib/src/phy/rf/CMakeFiles/srslte_rf.dir/all] Fehler 2
Makefile:160: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

**Comment by velichkov** [comment]
Hi @jonah01,

> i want to install srsLTE on an ubuntu 16.04 System, but the make process failed. I

> [ 41%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_zmq_imp.c.o
> /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c: In function ‘rf_zmq_tx’:
> /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:177:40: error: passing argument 2 of ‘zmq_recv’ from incompatible pointer type [-Werror=incompatible-pointer-types]
> n = zmq_recv(handler->transmitter, &dummy, sizeof(dummy), 0);
> ^
> In file included from /home/ubuntu/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:35:0:
> /usr/include/zmq.h:230:16: note: expected ‘zmq_msg_t * {aka struct *}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
> ZMQ_EXPORT int zmq_recv (void *s, zmq_msg_t *msg, int flags);
> ^

You probably have installed the older version of zeromq (`libzmq-dev`) which has incompatible C API. Installing the newer version (`libzmq3-dev` package in Ubuntu 16.04) should solve this problem

**Comment by jonah01** [comment]
Hi @velichkov,

Thank you for your fast answer, that was the problem.
Now it is working :)
