### ISSUE TITLE
srsue: should report long BSR in uplink if no data to transmit

### ISSUE THREAD

**Issue by cedric-roux** [srsLTE/srsLTE#353]
## Issue Description ##

Using openair eNB I see that srsUE is scheduled way too much, but it has no data to send. 

## Setup Details ##

Openair (hacked to remove the "permanent uplink scheduling" "feature" and fix some problems with SR detection) on one machine, a third party EPC on another. Srsue on a third (commit 5343b33f8ab2edf7319b6abb07bbc3970541517a). Radio over the air with b200 mini for srsUE and b210 for openair.

## Expected Behavior ##

The UE should not be scheduled in uplink.

## Actual Behaviour ##

The UE is scheduled.

## Steps to reproduce the problem ##

Run the setup, launch UE. Ping some machine and see too much uplink scheduling from openair eNB.

## Additional Information ##

In a dump of MAC traffic analysed with wireshark, I see that when the UE replies to the ping, it sends a short BSR (with size not 0, as if it was including in this size the bytes it sends in this uplink grant) for lcgid 1 (where we put drb 1) along with the data. And later on, it sends a short BSR with size 0 but for lcgid 0. So the eNB keeps thinking that the UE has some data to send on lcgid 1 and gives it uplink grants.

From my understanding, BSR is for data that is *not* transmitted with the packet. Say the UE has 12 bytes to send in its RLC buffers. It is scheduled so that it can send all of them in one grant. If it includes short BSR then the value should be 0, meaning "apart from the bytes in this grant, I have nothing else on this lcgid". But maybe my understanding of the specs is wrong.

In any case, I think it's a good idea to send a long BSR, ie. including the four lcgids with sizes set to 0 when the UE has nothing to send. That would be like "hey! my dear eNB friend! Thanks for granting some uplink to me, but I have nothing to transmit for the moment. See you when I have something to send!"

See https://eurecom.fr/~roux/srsue-extract.pcapng for a trace. We use the port 9999 method to analyse with wireshark. See https://gitlab.eurecom.fr/oai/openairinterface5g/wikis/T/wireshark for the configuration of wireshark.

Regards.

**Comment by andrepuschmann** [comment]
Hey Cedric, thanks for the detailed report. We've reworked UL MUX completely in the new version which will be released shortly. It would be good to run the experiment again with the new version. I'll close the issue for the moment. If it still persists, please reopen it again. Thanks
