### ISSUE TITLE
cell_search not working

### ISSUE THREAD

**Issue by 777arc** [srsLTE/srsLTE#355]
Just an FYI, I think the huge commit earlier in the year that added TDD broke (or partially broke) cell_search, because I can't get cell_search to actually find any cells, when using master, but when I checkout release_18_12 it finds the cells fine.

I'm also curious why cell_measurent was removed.

**Comment by jonah01** [comment]
Hi @777arc 

i have the same problem. 
Have you find a solution to run the latest version ? 
I am using the LimeSDR :)

**Comment by 777arc** [comment]
Nope, I just checked out the older version, since I didn't need TDD support anyway.  I was using a USRP B210.

**Comment by andrepuschmann** [comment]
Can you guys please reopen the issue and use the issue template and fill out all the information. Thanks

**Comment by 777arc** [comment]
I reopened one using the template
