### ISSUE TITLE
Q: MAC scheduling and TM3/4

### ISSUE THREAD

**Issue by GinesGarcia** [srsLTE/srsLTE#365]
Hi,
I've just started playing a bit with the different transmission modes available in srsLTE, but I was wondering if there is more detailed information about how MAC scheduler is behaving in both cases.

Any document/article for reading will be more than welcome :)

Thanks in advance,
Ginés.

**Comment by andrepuschmann** [comment]
Hey Ginés, I am afraid there is not full documentation available, except the in form of code. Feel free to ask a specific question on the list if you feel the need.
