### ISSUE TITLE
UE can not register to the network

### ISSUE THREAD

**Issue by mna110** [srsLTE/srsLTE#374]
Dear Technical Team
I have successfully built srslte and installed it . also programmed a simcard "sysmocom" as ue commercial .but when I want to connect to srslte while registering I get the following sentences:
Disconnecting rnti=0x3f2.
RACH:         tti=6001,  preamble=32,  offset=13,  temp_crnti=0x408
RACH:         tti=6001,  preamble=35,  offset=18,  temp_crnti=0x409
RACH:         tti=6001,  preamble=38,  offset=24,  temp_crnti=0x40a
and so on.

**Comment by andrepuschmann** [comment]
You cant connect with a sysmocom sim to a commercial network.
