### ISSUE TITLE
srsenb: error while loading shared libraries: libsrslte_rf.so: cannot open shared object file: No such file or directory    PLease Help

### ISSUE THREAD

**Issue by muratoznn** [srsLTE/srsLTE#375]
I can not start srslte Please Help me Why I am taking this error ?   srsenb: error while loading shared libraries: libsrslte_rf.so: cannot open shared object file: No such file or directory

**Comment by danicareardon** [comment]
Also having this issue

**Comment by MarkRohrbacher** [comment]
After installing the package with `suto make install`, try running `sudo ldconfig`.
