### ISSUE TITLE
srsLTE eMBMS support

### ISSUE THREAD

**Issue by fefer** [srsLTE/srsLTE#377]
Hi,

I saw this document:
https://buildmedia.readthedocs.org/media/pdf/srslte-docs/latest/srslte-docs.pdf

and the README stating about srs support for eMBMS. However, it was not clear, is it a support with the MCE, eMBMSGW and BM-SC? it is just stating that if I have all this elements the rest of the network (using srsLTE) will work accordingly?

Thanks!

**Comment by yagoda** [comment]
Hey,

The eMBMS gw is a separate binary that must be run in addition to the EPC and the eNodeB.  Some of the functionality of the MCE has been integrated into the eNodeB and MBMS-GW as this is a lightweight solution. As for the BMSC functionality, this is something that will be seen in later releases.  
You should be able to run a lightweight end-to-end eMBMS solution by following the instructions in the README. 
Let me know if you have trouble getting this up and running and I can help out!

Thanks,
Justin

**Comment by andrepuschmann** [comment]
Closing due to lack of responses from the original author.
