### ISSUE TITLE
Cat-M1 sample configuration files

### ISSUE THREAD

**Issue by james-nn** [srsLTE/srsLTE#404]
Hi Guys,

Do you guys have Cat-M1 sample configuration files?
There are Rel13 references in the code, like eDRX,mpdcch, so I assume Cat-M1 is supported and I’d only need the config files to set it up.
By the way this is a great project I could setup it up in 2 hours with a LimeSDR mini.
Just for curiosity I setup a bi-directional throughput test with iperf, with the default configuration.
I was getting 3.5Mbps UL and 13Mbps DL. Not bad considering that I was using the LimeSDR mini. 

Thanks,
James

**Comment by andrepuschmann** [comment]
Sorry James but we currently don't support Cat-M1.
