### ISSUE TITLE
[srsenb] throws "get_npucch(): Invalid parameters"

### ISSUE THREAD

**Issue by Lightchaos** [srsLTE/srsLTE#415]
Before filing an issue, search for solutions here:
- srsLTE users mailing list (http://www.softwareradiosystems.com/mailman/listinfo/srslte-users)

## Issue Description ##
As soon as I connect with my sysmocom custom SIM(using an iPhone SE), srsenb establishes a connection. Instead it throws the error "get_npucch(): Invalid parameters". After ~3-5 minutes srsenb just stops/crashes. I used the current master branch tag/release_19_09.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
The setup is as follows:
Running srsenb over Ettus Research B210 (driver: UHD_3.14.1.HEAD-0-g98c7c986)
OS: Ubuntu 18.04.3 LTS
UE is an iPhone SE with a programmable SIM from sysmocom 
I use ip-forwarding and nat to connect the connected phone to the internet.

## Expected Behavior ##
[What you expect to happen]
No get_npucch(): Invalid parameters exception in the console.

## Actual Behaviour ##
[What happens instead e.g. error message]
Spamming "get_npucch(): Invalid parameters" in the terminal I run srsenb from and srsenb stops/crashes after 3-5 minutes of spamming.

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]
Configs:
I added the SIM entry of my sysmocom SIM in user_db.csv.
I changed the in the mme section of enb.conf and epc.conf the values of mcc to 901 and the value of mnc to 70. I also changed the value of dl_earfcn in enb.conf to 1300.

Steps:
1. start sudo srsepc
2. start sudo srsenb
3. switch phone either on/off or turn flight mode on/off so your phone looks for a network
4. as soon as the phone connects to the enb, the terminal throws "get_npucch(): Invalid parameters" multiple times.

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]
To verify I didn't do anything wrong, I used the tag/release_19_06 to check if it works. It works fine there, with no "get_npucch(): Invalid parameters" exception thrown. The outputs of the terminal, log as well as pcap are attached.

[Outputs.zip](https://github.com/srsLTE/srsLTE/files/3890829/Outputs.zip)

**Comment by xavierarteaga** [comment]
Thanks, this issue should have been fixed for next release.
