### ISSUE TITLE
PLease Help Can Not Working Limesdr mini ?

### ISSUE THREAD

**Issue by muratoznn** [srsLTE/srsLTE#428]
How Can I Fix This Error ? Please Help ?

root@kali:/etc/srslte# sudo srsenb /etc/srslte/enb.conf
Starting with SSE4.2 extension
---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /etc/srslte/enb.conf...
No Soapy devices found.
Error opening RF device
Failed to find device soapy with args rxant=LNAH,txant=BAND2

I configured enb.conf like this 

[rf]
dl_earfcn = 3050
tx_gain = 56
rx_gain = 38

device_name = soapy
device_args =  rxant=LNAH,txant=BAND2
time_adv_nsamples = 70
burst_preamble_us = 0

**Comment by andrepuschmann** [comment]
I would start with installing the Lime drivers
