### ISSUE TITLE
Non Reception of srsLTE signals on commercial Phone

### ISSUE THREAD

**Issue by asp2k5** [srsLTE/srsLTE#436]
Can someone please help out.
I am trying to connect my commercial phone to **srsLTE build using USRP B210.**
Am **not getting any LTE signal on my phone,** even though **SRS enb and epc 
are both running on pc.** can anyone pls let know where am going wrong?

kindly help out . thanks.

**Comment by andrepuschmann** [comment]
No background information is given. It can be a thousand things. Closing issue.
