### ISSUE TITLE
SIB10 and SIB11

### ISSUE THREAD

**Issue by Dastgsm** [srsLTE/srsLTE#446]
Hello,

I would like to use sib10 and sib11 on sib.conf of srslte .
the first step is to adding on  si_mapping_info = [10, 11];

but my big problem is to specify the parameter of sib10:
messageidenfitier
serialnumber
warningtype[0]
warningtype[1]
dummysize

or to specify the parameter of sib11 :
messageidenfitier
serialnumber
segmentsize
datacodingschema
warningsegmentmessagetype

Chears,

**Comment by andrepuschmann** [comment]
You also need to add the parsing of the new SIB values. Take a look at the current code and how it's done for other SIBs. Thanks
