### ISSUE TITLE
Unused variable "norm" in lib/src/phy/mimo/precoding.c if DISABLE_SIMD: ON

### ISSUE THREAD

**Issue by zariok** [srsLTE/srsLTE#455]
## Issue Description ##
lib/src/phy/mimo/precoding.c#1140
`
float norm = 2.0f / scaling;
`

This is unused if DISABLE_SIMD: ON thus causing compile failure due to no-unused-variables.

## Expected Behavior ##
Build succeeds without modification of source

## Actual Behaviour ##
Build fails due to -Wno-unused-variables

## Steps to reproduce the problem ##
Set DISABLE_SIMD ON, cmake and build

**Comment by andrepuschmann** [comment]
Fixed in new 20.04 release.
