### ISSUE TITLE
problem with srsEnb

### ISSUE THREAD

**Issue by theabyssover** [srsLTE/srsLTE#458]
Hello im in master branch (d045213) , i try running srsEnb on B200mini .
I`m new to lte, so i just used default configs made by srslte_install_configs.sh user
SrsEpc start ok.
But srsEnb crashes right after start.

Reading configuration file /home/igor/.config/srslte/enb.conf...
Opening 1 RF devices with 1 RF channels...
[INFO] [UHD] linux; GNU C++ version 4.8.4; Boost_105400; UHD_3.14.0.HEAD-0-g6875d061
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP with args: type=b200,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B200mini
[INFO] [B200] Operating over USB 2.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
[WARNING] [MULTI_USRP] The total sum of rates (23.040000 MSps on 1 channels) exceeds the maximum capacity of the connection.
This can cause overflows (O).
[WARNING] [MULTI_USRP] The total sum of rates (23.040000 MSps on 1 channels) exceeds the maximum capacity of the connection.
This can cause underruns (U).
Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz
Setting Sampling frequency 11.52 MHz
Failed to initiate SCTP socket. Attempting reconnection in 10 seconds

==== eNodeB started ===
Type <t> to view trace
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_S_create
srsLTE crashed... backtrace saved in './srsLTE.backtrace.crash'...
---  exiting  ---

backtrace.crash is here

--- command='srsenb' version=19.12.0 signal=6 date='20/02/2020 15:27:19' ---
	srsenb() [0x647d2e]
	/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0) [0x7f310c7dccb0]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37) [0x7f310c7dcc37]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x148) [0x7f310c7e0028]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x155) [0x7f310d0ea535]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5e6d6) [0x7f310d0e86d6]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x5d799) [0x7f310d0e7799]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x52a) [0x7f310d0e834a]
	/lib/x86_64-linux-gnu/libgcc_s.so.1(+0xffd3) [0x7f310cb7dfd3]
	/lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_RaiseException+0xfb) [0x7f310cb7e35b]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_throw+0x65) [0x7f310d0e8915]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZSt20__throw_length_errorPKc+0x67) [0x7f310d13a3a7]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xba262) [0x7f310d144262]
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSs9_M_mutateEmmm+0x56) [0x7f310d1443d6]
	/usr/local/lib/libuhd.so.3.14.0(uhd_tx_streamer_send+0x3b) [0x7f310bd9e1fb]
	/usr/local/lib/libsrslte_rf.so(rf_uhd_send_timed_multi+0x1a7) [0x7f310d7a0157]
	/usr/local/lib/libsrslte_rf.so(srslte_rf_send_timed_multi+0x2e) [0x7f310d79cdde]
	srsenb(_ZN6srslte5radio2txEPPCfj18srslte_timestamp_t+0xb8) [0x724d48]
	srsenb(_ZN6srsenb10phy_common10worker_endEjPPCfj18srslte_timestamp_t+0x91) [0x5cfda1]
	srsenb(_ZN6srsenb9sf_worker8work_impEv+0x378) [0x5c5f08]
	srsenb(_ZN6srslte11thread_pool6worker10run_threadEv+0x119) [0x6595c9]
	srsenb(_ZN6thread21thread_function_entryEPv+0x1d) [0x5afdbd]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7f310e3d3184]
	/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f310c8a3bed]

can you give me any suggestions please.

**Comment by andrepuschmann** [comment]
Use USB3. USB2 isn't enough.
