### ISSUE TITLE
srsENB keeps running even if GTPU addr bind() fials

### ISSUE THREAD

**Issue by pespin** [srsLTE/srsLTE#460]
I was setting up srsENB and srsEPC on the same machine and using same IP address, and then due to GTP using same port, bind() on the srsENB (started after srsEPC) was failing with "Address already in use" (I submitted a patch to print the error information on bind() failure).
The problem is that despite printing the error, srsENB simply continues running and does not exit with an error. In my opinion that's a fatal error which will prevent srsENB from working correctly, and not exiting will hide the issue to the operator. It's specially important since that's not a temporary user (afaik srsENB won't try to re-bind at any point later), so it really requires the issue to be fixed and the process be relaunched.

Expected behavior:
If tun or socket creation is requested and fails for any reason, srsENB should exit with an error so the issue can be seen and fixed quickly.

Related code: gtpu.cc gtpu::init().

**Comment by andrepuschmann** [comment]
Thanks for reporting. It should be fixed in the new release.
