### ISSUE TITLE
XTRX (soapy): unable to set samplerate

### ISSUE THREAD

**Issue by dchard** [srsLTE/srsLTE#462]
I am trying to set up a 5MHz LTE enb with srsLTE and XTRX via Soapy, and I always got the same error message:

```
Setting Sampling frequency 5.76 MHz
21:13:57.571940 INFO:   [LMSF] PCI:/dev/xtrx0: Increase RXdiv= 5 TXdiv= 8 => CGEN 122.9 Mhz
21:13:57.574585 INFO:   [LMSF] PCI:/dev/xtrx0: Increase RXdiv=10 TXdiv=16 => CGEN 245.8 Mhz
21:13:57.574590 INFO:   [LMSF] PCI:/dev/xtrx0: Increase RXdiv=21 TXdiv=32 => CGEN 491.5 Mhz
21:13:57.574594 ERROR:  [LMSF] PCI:/dev/xtrx0: can't deliver decimation: 21 of 491.520 MHz CGEN and 5.760 MHz samplerate; TXm = 0.000 RXm = 0.000
[ERROR] SoapyXTRX::setSampleRate(0, RX, 5.76 MHz) - error -22
setSampleRate Rx fail: SoapyXTRX::setSampleRate() unable to set samplerate!
```

I tried with PRB 25, 50 and 100, always the same result.

It attached the full log + the "SoapySDRUtil --probe" output, hope someone can help me with this.

Two of us already raised this at XTRX (https://github.com/xtrx-sdr/images/issues/68), no answer arrived. I am not sure if this is a srLTE or an XTRX issue.

[soapy_probe.txt](https://github.com/srsLTE/srsLTE/files/4239875/soapy_probe.txt)
[srsenb_log.txt](https://github.com/srsLTE/srsLTE/files/4239876/srsenb_log.txt)

**Comment by andrepuschmann** [comment]
Our SoapySDR RF driver works with multiple other devices, including the bladeRF, limesdr and USRP B210. So, frankly speaking, I don't see why this should be a srsLTE related issue.
