### ISSUE TITLE
make test failed: 218 - pucch_test (SEGFAULT)

### ISSUE THREAD

**Issue by esraltun** [srsLTE/srsLTE#467]
Hi, I have installed libiio, libad9361, SoapySDR (version 0.7.2), SoapyPlutoSDR and srsLTE. It failed when I ran make test command 

99% tests passed, 1 tests failed out of 587

Total Test time (real) = 231.43 sec

The following tests FAILED:
	218 - pucch_test (SEGFAULT)
Errors while running CTest
Makefile:149: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by andrepuschmann** [comment]
Can't reproduce this. Please provide build details, i.e. CPU, compiler, etc.
