### ISSUE TITLE
srslte crashed running at zc702 

### ISSUE THREAD

**Issue by esraltun** [srsLTE/srsLTE#468]
Hi ,
I'm trying to run srsLTE on xilinx ZC702. I'm using soapysdr driver and soapyplutosdr. 
srsLTE (18.12.0)
I'm facing following issue when I run it srsENB, 
Built in Release mode using commit d045213 on branch master.

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /etc/srslte/enb.conf...
Opening 1 RF devices with 1 RF channels...
Soapy has found device #0: device=plutosdr, driver=plutosdr, uri=local:, 
srsLTE crashed... backtrace saved in './srsLTE.backtrace.crash'...
---  exiting  ---

**Comment by andrepuschmann** [comment]
While it certainly shouldnt segfault, please send a backtrace or run in gdb if possible, it still won't work on board due to missing timestamp support in libiio, etc.
We therefore don't support this platform in the public release. Closing this issue therefore
