### ISSUE TITLE
make syntax error rf_zmq_imp.c:355

### ISSUE THREAD

**Issue by RFworrior** [srsLTE/srsLTE#470]
Before filing an issue, search for solutions here:
- srsLTE users mailing list (http://www.softwareradiosystems.com/mailman/listinfo/srslte-users)

## Issue Description ##
When running "sudo make", there is a syntax erorr:

[ 45%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_zmq_imp.c.o
/home/amit/Projects/srsLTE/lib/src/phy/rf/rf_zmq_imp.c: In function ‘rf_zmq_open_multi’:
/home/amit/Projects/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:355:24: error: implicit declaration of function ‘zmq_ctx_new’ [-Werror=implicit-function-declaration]
     handler->context = zmq_ctx_new();
                        ^
/home/amit/Projects/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:355:22: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     handler->context = zmq_ctx_new();
                      ^
/home/amit/Projects/srsLTE/lib/src/phy/rf/rf_zmq_imp.c: In function ‘rf_zmq_close’:
/home/amit/Projects/srsLTE/lib/src/phy/rf/rf_zmq_imp.c:497:5: error: implicit declaration of function ‘zmq_ctx_destroy’ [-Werror=implicit-function-declaration]
     zmq_ctx_destroy(handler->context);
     ^
cc1: all warnings being treated as errors
lib/src/phy/rf/CMakeFiles/srslte_rf.dir/build.make:110: recipe for target 'lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_zmq_imp.c.o' failed
make[2]: *** [lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_zmq_imp.c.o] Error 1
CMakeFiles/Makefile2:3316: recipe for target 'lib/src/phy/rf/CMakeFiles/srslte_rf.dir/all' failed
make[1]: *** [lib/src/phy/rf/CMakeFiles/srslte_rf.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

## Setup Details ##
Using Ubuntu 16.04.6 LTS
BladeRF A9

ladeRF-cli version:        1.8.0-git-4552101-dirty
libbladeRF version:         2.2.1-git-4552101-dirty
Firmware version:           2.3.2
FPGA version:               0.10.2 (configured by USB host)

## Expected Behavior ##
In previous builds, the make did work fine.

## Actual Behaviour ##
Got syntax error.

## Steps to reproduce the problem ##
sudo apt-get install cmake libfftw3-dev libmbedtls-dev libboost-program-options-dev libconfig++ dev libsctp-dev
sudo add-apt-repository ppa:bladerf/bladerf
sudo apt-get update
sudo apt-get install bladerf
apt-get install libsctp-dev lksctp-tools
git clone https://github.com/srsLTE/srsLTE.git
cd srsLTE
mkdir build
cd build
cmake ../
make <- ERROR
make test

## Additional Information ##

**Comment by andrepuschmann** [comment]
We don't actively support Ubuntu 16.04 anymore. It may or may not work. Better update to 18.04. and make sure you have the ZMQ dev library installed. Try if you can follow [this](https://docs.srslte.com/en/latest/app_notes/source/zeromq/source/index.html#zeromq-appnote) guide.
