### ISSUE TITLE
No gw.netns function in srsue

### ISSUE THREAD

**Issue by Phil-anthropy** [srsLTE/srsLTE#471]
After following guidance on running a full end-to-end LTE instance on a single computer the gw.netns function is not implemented -

ubuntu@ubuntu:~$ sudo srsue --rf.device_name=zmq --rf.device_args="tx_port=tcp://10.10.10.3:5554,rx_port=tcp://10.10.10.3:5555,id=ue,base_srate=23.04e6" --gw.netns=ue1 --phy.nof_phy_threads=1
unrecognised option '--gw.netns=ue1'

ubuntu@ubuntu:~$ srsue -v
Version 19.12.0

ubuntu@ubuntu:~$ srsue -h | grep rf.device
  --rf.device_name arg (=auto)          Front-end device name
  --rf.device_args arg (=auto)          Front-end device arguments
  --rf.device_args_2 arg (=auto)        Front-end device 2 arguments
  --rf.device_args_3 arg (=auto)        Front-end device 3 arguments

ubuntu@ubuntu:~$ srsue -h | grep gw.
  --log.gw_level arg                    GW log level
  --log.gw_hex_limit arg                GW log hex dump limit
  --gw.ip_devname arg (=tun_srsue)      Name of the tun_srsue device
  --gw.ip_netmask arg (=255.255.255.0)  Netmask of the tun_srsue device

**Comment by andrepuschmann** [comment]
You're right. The netns has been added very recently. Although the docs already include it it won't be available until 20.04 publicly. You can run the UE in another namespace still with "sudo ip exec netns ue1 srsue". Hope that helps and sorry for the inconvenience.
