### ISSUE TITLE
Lte Registration Problem Help Please ?

### ISSUE THREAD

**Issue by muratoznn** [srsLTE/srsLTE#472]
I started srsepc and srsenb but I can not connect to base station . For it I have to need another sdr and srsue ? Or How I can register my imsi number to my 4g base station ? How Can I add it ?

**Comment by alvasMan** [comment]
This is does not seem like an issue, please use the mailing list for support.
Please add logs and relevant information so we can help.

See the docs on how to add an user to the ue_db.csv:
https://docs.srslte.com/en/latest/srsepc/source/2_epc_getstarted.html#adding-an-ue-to-hss-database
