### ISSUE TITLE
Decode the SIB message in srslte

### ISSUE THREAD

**Issue by p3ngdump** [srsLTE/srsLTE#478]
Hello,

Has anyone solved the problem which decode the additional SIB message in srslte?
Except the SIB1, SIB2 message.

I want decode the additional SIB message(SIB5, SIB10 .. etc)
Can tell me how to do decode additional SIB messages?

Guessing, It seems to be solved by modify the enb_cfg_parser.cc, enb_cfg_parser.h

If you know the solve method, please tell me

Thank you.

**Comment by andrepuschmann** [comment]
The SIBs that the UE decodes are defined [here](https://github.com/srsLTE/srsLTE/blob/d045213fb9cbf98c83c06d7c17197a9dcbfddacf/srsue/src/stack/rrc/rrc.cc#L44). You can add what ever you want but the eNB may or may not transmit them.
