### ISSUE TITLE
srsue attched eNB+EPC, but it released from the network soon.

### ISSUE THREAD

**Issue by jin-github1002** [srsLTE/srsLTE#482]
hello everyone, I have an issue about srsue releasing from the network automatically soon.

I ran srsue in a machine , ran eNB and EPC in another machine.  A limeSDR USB is used in every machine as RF end. on the ue machine, i just use srsue without usim card. I think it will use the user info in the ue.conf, such as IMSI. 

In the terminals of srsue, enb and epc, i can see that the ue has attached the network. But it released from the network automatically soon. 

Does anybody know why it is not on the network for a long time?

Thanks for your help.

the output of ue is as follows:

Reading configuration file ue.conf...

Built in Release mode using commit d045213f on branch master.

Opening 1 RF devices with 1 RF channels...
Soapy has found device #0: addr=1d50:6108, driver=lime, label=LimeSDR-USB [USB 3.0] 9081C05C13425, media=USB 3.0, module=FX3, name=LimeSDR-USB, serial=0009081C05C13425,
[INFO] Make connection: 'LimeSDR-USB [USB 3.0] 9081C05C13425'
[INFO] Reference clock 30.72 MHz
[INFO] Device name: LimeSDR-USB
[INFO] Reference: 30.72 MHz
[INFO] LMS7002M register cache: Disabled
Setting up Rx stream with 1 channel(s)
Setting up Tx stream with 1 channel(s)
[INFO] RX LPF configured
[INFO] RX LPF configured
Set Rx bandwidth to 2.50 MHz
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 5 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Set Tx bandwidth to 5.00 MHz
[INFO] Filter calibrated. Filter order-2nd, set to 50 MHz
[INFO] TX LPF configured
Set Tx bandwidth to 50.00 MHz
Available device sensors:
 - clock_locked
 - lms7_temp
Available sensors for Rx channel 0:
 - lo_locked
[INFO] Tx calibration finished
[INFO] Rx calibration finished
State of gain elements for Rx channel 0 (AGC not supported):
 - TIA: 9.00 dB
 - LNA: 30.00 dB
 - PGA: -4.00 dB
State of gain elements for Tx channel 0 (AGC not supported):
 - PAD: 45.00 dB
 - IAMP: 0.00 dB
Rx antenna set to LNAL
Tx antenna set to BAND1

Warning burst preamble is not calibrated for device lime. Set a value manually

Waiting PHY to initialize ... done!
Attaching UE...
Searching cell in DL EARFCN=3400, f_dl=2685.0 MHz, f_ul=2565.0 MHz
Set Rx bandwidth to 2.50 MHz
[INFO] Rx calibration finished
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 5 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Set Tx bandwidth to 5.00 MHz
[INFO] Filter calibrated. Filter order-2nd, set to 50 MHz
[INFO] TX LPF configured
Set Tx bandwidth to 50.00 MHz
[INFO] Tx calibration finished
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=0.4 KHz
[INFO] RX LPF configured
Set Rx bandwidth to 11.52 MHz
[INFO] Rx calibration finished
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 11.52 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Set Tx bandwidth to 11.52 MHz
[INFO] Filter calibrated. Filter order-2nd, set to 50 MHz
[INFO] TX LPF configured
Set Tx bandwidth to 50.00 MHz
[INFO] Tx calibration finished
RF status: O=0, U=0, L=2
[INFO] RX LPF configured
Set Rx bandwidth to 2.50 MHz
[INFO] Rx calibration finished
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 5 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Set Tx bandwidth to 5.00 MHz
[INFO] Filter calibrated. Filter order-2nd, set to 50 MHz
[INFO] TX LPF configured
Set Tx bandwidth to 50.00 MHz
[INFO] Tx calibration finished
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=0.1 KHz
[INFO] RX LPF configured
Set Rx bandwidth to 11.52 MHz
[INFO] Rx calibration finished
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 11.52 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
[INFO] TX LPF configured
Set Tx bandwidth to 11.52 MHz
[INFO] Filter calibrated. Filter order-2nd, set to 50 MHz
[INFO] TX LPF configured
Set Tx bandwidth to 50.00 MHz
[INFO] Tx calibration finished
RF status: O=0, U=0, L=1
Found PLMN:  Id=00101, TAC=7
Random Access Transmission: seq=32, ra-rnti=0x2
Random Access Complete.     c-rnti=0x46, ta=0
RRC Connected
Network attach successful. IP: 172.16.0.2
Software Radio Systems LTE (srsLTE)
RF status: O=0, U=0, L=1
RF status: O=0, U=0, L=1
RF status: O=0, U=0, L=1
RF status: O=0, U=0, L=2
RF status: O=0, U=0, L=2
RF status: O=0, U=0, L=1
RF status: O=0, U=0, L=1
RF status: O=0, U=0, L=1
RF status: O=0, U=0, L=2
Warning: Detected Radio-Link Failure
[INFO] RX LPF configured
LSet Rx bandwidth to 2.50 MHz
[INFO] Rx calibration finished
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 5 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
RF status: O=0, U=1, L=1
[INFO] TX LPF configured
Set Tx bandwidth to 5.00 MHz
[INFO] Filter calibrated. Filter order-2nd, set to 50 MHz
[INFO] TX LPF configured
Set Tx bandwidth to 50.00 MHz
[INFO] Tx calibration finished
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=0.6 KHz
[INFO] RX LPF configured
Set Rx bandwidth to 11.52 MHz
[INFO] Rx calibration finished
[INFO] Filter calibrated. Filter order-4th, filter bandwidth set to 11.52 MHz.Real pole 1st order filter set to 2.5 MHz. Preemphasis filter not active
RF status: O=0, U=2, L=0
[INFO] TX LPF configured
Set Tx bandwidth to 11.52 MHz
[INFO] Filter calibrated. Filter order-2nd, set to 50 MHz
[INFO] TX LPF configured
Set Tx bandwidth to 50.00 MHz
[INFO] Tx calibration finished
RF status: O=0, U=3, L=2
RF status: O=0, U=2, L=0
RF status: O=0, U=3, L=0
RF status: O=0, U=2, L=0
RF status: O=0, U=3, L=0
RF status: O=0, U=2, L=0
RF status: O=0, U=3, L=0
RF status: O=0, U=2, L=0
RF status: O=0, U=3, L=0
RF status: O=0, U=2, L=0
RF status: O=0, U=3, L=0
RF status: O=0, U=2, L=0
RF status: O=0, U=3, L=0
RF status: O=0, U=2, L=0
RF status: O=0, U=3, L=0
RF status: O=0, U=2, L=0
^CStopping srsUE... Press Ctrl+C 9 more times to force stop
RF status: O=0, U=3, L=0
---  exiting  ---

**Comment by andrepuschmann** [comment]
no cross-posting on github an mailing list please
