### ISSUE TITLE
wrong parsing of "enb_id" in srsenb .cfg

### ISSUE THREAD

**Issue by pespin** [srsLTE/srsLTE#485]
srsENB seems to always be handling the content of "enb_id" attribute in config file as a hex value, even if a decimal value is passed. For instance, add id 0x19B (411 decimal) to config file:
`enb_id = 411`

srsENB will parse that as 0x411 instead as of 411 decimal (0x19B), as can be sen by srsEPC stdout output:
`S1 Setup Request - eNB Name: srsenb01, eNB id: 0x411`

**Comment by andrepuschmann** [comment]
Thanks for flagging Pau. Fixed in next
