### ISSUE TITLE
after ue attched, wifi of the computer whre the eNB+epc are on dose not work.

### ISSUE THREAD

**Issue by jin-github1002** [srsLTE/srsLTE#492]
## Issue Description ##
Hi ,All
I use two LimeSDR as the RF end to build LTE network.  One Limesdr is for ue. The other one is for eNB. Two computers run as ue and eNB+epc. 
Now the ue can attch the network( about 5 minutes). When ue attached successfully, i hope to test : set the default gateway on ue(sudo route add default gw 172.16.0.1 tun_srsue), set the net forward on epc(sudo srsLTE/srsepc/srsepc_if_masq.sh wlp2s0), then if I open a website on ue, the website can be reached out. 

But My test failed. The wifi on the computer where epc is does not work. there is a ? that i can see. I can not ping any website anymore. 
i can use ifconfig to see the wifi ip address.
if i stop srslte, pull out the limesdr, the wifi on the epc computer returns to be ok. 

Does anybody know the reason and how to deal with it?

Any help will be appreciated. Thanks

**Comment by andrepuschmann** [comment]
I am having difficulties to understand the question but it doesn't seem to be a srsLTE issue but rather some misconfiguration. Feel free to reopen if you can explain why you think it is srsLTE related.
