### ISSUE TITLE
srsUE and LimeSDR Mini: gain settings?

### ISSUE THREAD

**Issue by okallio** [srsLTE/srsLTE#495]
Hi!

Running Ubuntu 18.04 and srsLTE 19.12. 

Primarily trying to achieve stable performance using srsUE with commercial BTS. Basically srsUE can attach to BTS and gets IP and ping works. But attachment is very fragile. Perhaps only 1 time out of 5 succeeds. So something needs to be tweaked?

How gain setting is supposed to work in srsUE? Despite changing tx_gain or rx_gain in ue.conf there is always same values in TIA, LNA etc when srsUE is started ?

   "State of gain elements for Rx channel 0 (AGC not supported):
    TIA: 9.00 dB
    LNA: 30.00 dB
    PGA: -4.00 dB
    State of gain elements for Tx channel 0 (AGC not supported):
    PAD: 45.00 dB
    IAMP: 0.00 dB"

Are TIA, LNA etc supposed to be adjustable or are they fixed somewhere in srsLTE code? If so can they be changed before compilation?

Also there is this strange error on TX:

   "[ERROR] Tx Calibration: MCU error 4 (SXT tune failed)
    [INFO] Rx calibration finished"

This TX cal error seems to be quite common but if there is a fix for this would be happy to hear.

BR, Oula

**Comment by andrepuschmann** [comment]
The questions you are asking are a better fit for the Lime mailing list or forums really. If you'd posted some logs of the UE we could at least have a look at the signal measurements. But with the amount of provided info it is impossible to say anything. Closing issue therefore.
