### ISSUE TITLE
Can i capture the SIB5 message?

### ISSUE THREAD

**Issue by p3ngdump** [srsLTE/srsLTE#499]
Hello srsLTE.

Recently, i'm modified the enb_cfg_parser.cc, sib.conf and rrc.cc(UE side)
So, i can capture the SIB messages.

But, i don't know how to capture the SIB5 message

As far as I know, SIB5 message is not default define message
So, it need modify the enb_cfg_parser.cc, sib.conf and rrc.cc(UE side)

Can i get the sample code(relate the SIB5 message)?

+

It is my parse_sib5 function in enb_cfg_parser.cc
int parse_sib5(std::string filename, sib_type5_s* data)
{
  parser::section sib5("sib5");

  parser::section carrier_freq_l("inter_freq_carrier_freq_list");
  sib5.add_subsection(&carrier_freq_l);

  parser::section carrier_freq("inter_freq_carrier_freq_info");
  carrier_freq_l.add_subsection(&carrier_freq);

  carrier_freq.add_field(new parser::field<uint8>("dl_carrier_freq", &data->inter_carrier_list[0].dl_carrier_freq));
  carrier_freq.add_field(new parser::field<int8>("q_rx_lev_min", &data->inter_freq_carrier_freq_list[0].q_rx_lev_min));
  carrier_freq.add_field(new parser::field<int8>("p_max", &data->inter_freq_carrier_freq_list[0].p_max));
  carrier_freq.add_field(new parser::field<uint8>("t_resel_eutra", &data->inter_freq_carrier_freq_list[0].t_resel_eutra));
  carrier_freq.add_field(new parser::field<uint8>("thresh_x_high", &data->inter_freq_carrier_freq_list[0].thresh_x_high));
  carrier_freq.add_field(new parser::field<uint8>("thresh_x_low", &data->inter_freq_carrier_freq_list[0].thresh_x_low));

  carrier_freq.add_field(make_asn1_enum_str_parser("allowed_meas_bw", &data->inter_freq_carrier_freq_list[0].allowed_meas_bw));
  carrier_freq.add_field(new parser::field<bool>("presence_ant_port1", &data->inter_freq_carrier_freq_list[0].presence_ant_port1));

  carrier_freq.add_field(new parser::field<uint8>("cell_resel_prio", &data->inter_freq_carrier_freq_list[0].cell_resel_prio));
  carrier_freq.add_field(make_asn1_bitstring_number_parser("neigh_cell_cnfg", &data->inter_freq_carrier_freq_list[0].neigh_cell_cfg));
  carrier_freq.add_field(make_asn1_enum_str_parser("q_offset_freq", &data->inter_freq_carrier_freq_list[0].q_offset_freq));
  return parser::parse_section(std::move(filename), &sib5);
}

when run the srsenb, it is print below comment.
sudo srsenb --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://192.168.28.143:2001,id=enb"

Built in Release mode using commit d045213f on branch master.

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /home/p3ngdump/.config/srslte/enb.conf...
srsLTE crashed... backtrace saved in './srsLTE.backtrace.crash'...

Thank all

**Comment by andrepuschmann** [comment]
I am afraid we can't debug your code here but I guess with GDB you can identify your issue. Thanks
