### ISSUE TITLE
The following tests FAILED: 	724 - nas_test (Child aborted)

### ISSUE THREAD

**Issue by WT4444** [srsLTE/srsLTE#507]
After makeing  test ，an error occurred:The following tests FAILED: 	724 - nas_test (Child aborted),Errors while running CTest

**Comment by andrepuschmann** [comment]
no further background provided. impossible to check

**Comment by WT4444** [comment]
After I finish installing srslte, when I execute the make test command,an error occurred:The following tests FAILED: 724 - nas_test (Child aborted),Errors while running CTest。

**Comment by WT4444** [comment]
> no further background provided. impossible to check
According to the official website tutorial, after installing the uhd driver and related dependent libraries on ubuntu18.04, execute the install srsLTE command and execute the make test command prompt The following tests FAILED: 724-nas_test (Child aborted)
