### ISSUE TITLE
Huawei DBS3900

### ISSUE THREAD

**Issue by rembulan** [srsLTE/srsLTE#513]
is there any one use srsLTE with Huawei DBS3900 can share their experience

**Comment by andrepuschmann** [comment]
Please use the mailing list for general questions like this. The issue tracker is there for hunting bugs, etc.

**Comment by rembulan** [comment]
Thank You for your suggestionsPada tanggal 8 Jul 2020 15.15, Andre Puschmann <notifications@github.com> menulis:
Please use the mailing list for general questions like this. The issue tracker is there for hunting bugs, etc.
