### ISSUE TITLE
Failed to initiate SCTP socket. 

### ISSUE THREAD

**Issue by WT4444** [srsLTE/srsLTE#516]
## Issue Description ##
Install srsLTE on Ubuntu 8.04 according to the official website tutorial. After the installation is complete, execute the srsenb command, warnings and errors appear: [WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24266666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24266666

connect(): Connection refused
Failed to initiate SCTP socket. Attempting reconnection in 10 seconds

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions
Installed uhd driver and related dependencies according to the official website tutorial。
 Operation System：Ubuntu18.04
Hardware：USRP2943R
## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 24266666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=24266666
[INFO] [0/DUC_1] Initializing block control (NOC ID: 0xD0C0000000000000)

Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz for cc_idx=0
connect(): Connection refused
Failed to initiate SCTP socket. Attempting reconnection in 10 seconds

**Comment by andrepuschmann** [comment]
likely EPC/eNB config issue. Please check ports etc and double check you have SCTP support compiled in and your kernel supports SCTP ports.
