### ISSUE TITLE
Error receiving from UHD: 30

### ISSUE THREAD

**Issue by anhtrung87vn** [srsLTE/srsLTE#524]
## Issue Description ##
[Describe the issue in detail]
Hi,
after running the command "sudo ../build/srsenb/src/srsenb ./enb.conf"
I see the below issue continuously:
"
Built in Release mode using commit d045213fb on branch HEAD.

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file ./enb.conf...
Opening 1 RF devices with 1 RF channels...
[INFO] [UHD] linux; GNU C++ version 7.4.0; Boost_106501; UHD_3.14.1.1-release
[INFO] [LOGGING] Fastpath logging disabled at runtime.
[INFO] [B200] Loading firmware image: /usr/share/uhd/images/usrp_b200_fw.hex...
Opening USRP with args: type=b200,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Loading FPGA image: /usr/share/uhd/images/usrp_b210_fpga.bin...
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Detecting internal GPSDO.... 
[INFO] [GPS] No GPSDO found
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Setting frequency: DL=2685.0 Mhz, UL=2565.0 MHz
Setting Sampling frequency 11.52 MHz

==== eNodeB started ===
Type <t> to view trace
/home/lte/srsLTE/lib/src/phy/rf/rf_uhd_imp.c.896: Error code 0xf was returned during streaming. Aborting.

[ERROR] [STREAMER] The receive packet handler caught a value exception.
ValueError: bad vrt header or packet fragment
[ERROR] [STREAMER] recv packet demuxer unexpected sid 0x70001
/home/lte/srsLTE/lib/src/phy/rf/rf_uhd_imp.c.876: Error receiving from UHD: 30

/home/lte/srsLTE/lib/src/phy/rf/rf_uhd_imp.c.113: USRP reported the following error: None

/home/lte/srsLTE/lib/src/phy/rf/rf_uhd_imp.c.876: Error receiving from UHD: 30

/home/lte/srsLTE/lib/src/phy/rf/rf_uhd_imp.c.113: USRP reported the following error: None

/home/lte/srsLTE/lib/src/phy/rf/rf_uhd_imp.c.876: Error receiving from UHD: 30
## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]
There is no UHD error
## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]
Setup:
$ git clone https://github.com/srsLTE/srsLTE.git
$ cd srsLTE
$ git checkout release_19_12
$ git rev-parse HEAD
d045213fb9cbf98c83c06d7c17197a9dcbfddacf
$ mkdir build
$ cd build
$ cmake ../
$ make
$ make test
$ cd srsenb/
$ sudo ../build/srsenb/src/srsenb ./enb.conf
[enb.conf.txt](https://github.com/srsLTE/srsLTE/files/4925632/enb.conf.txt)

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
This is a UHD error. Closing therefore.
