### ISSUE TITLE
Network with srsLTE and USRP B200

### ISSUE THREAD

**Issue by joelsernamoreno** [srsLTE/srsLTE#525]
Hello!
I installed the latest version of srsLTE with USRP B200

I am using the configuration examples included in the repository, these files have been renamed and copied to the .config/srslte/ directory

I now execute srsepc and srsenb.  Srslte recognizes the configuration files and doesn't give any problem, the USRP leds light up and everything seems to work correctly, but... my mobile doesn't see the LTE node

I've tried several mobiles and none of them see the node

I have also adjusted TX and RX in the configuration files, but it still doesn't work

Thank you!

**Comment by andrepuschmann** [comment]
Hey, please have a look at our COTS UE appnote https://docs.srslte.com/en/latest/app_notes/source/cots_ue/source/index.html#cots-ue-appnote
If the issue remains, please reopen this ticket and provide more info including logs, etc.
