### ISSUE TITLE
could not create sctp 

### ISSUE THREAD

**Issue by jin-github1002** [srsLTE/srsLTE#528]
hi ,all
I run srs epc. It says " could not create sctp". 

the compiling info is as follows. I do install lksctp-tools ( donwload binary , ./bootstrap, ./configure , make -j4, sudo make install). But it says:--   No package 'sctp' found

srsLTE is run on Jetson TX2. arm processor. I have checked modules in Linux kernel. I dont know if the modules are what srslte needs.

Could anyone help with this? Any help will be appreciated.

----------check modules in Linux kernel
nvidia@nvidia-desktop:~$ lsmod | grep sctp
nf_conntrack_proto_sctp    14044  0
nf_conntrack          105820  1 nf_conntrack_proto_sctp

------------compiling info---------------

nvidia@nvidia-desktop:~/srsLTE1812/build$ cmake ../
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_SYSTEM: Linux-4.9.140-tegra
-- CMAKE_SYSTEM_PROCESSOR: aarch64
-- CMAKE_CXX_COMPILER: /usr/bin/c++
-- Build type not specified: defaulting to Release.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (mkl) does
  not match the name of the calling package (MKL).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindMKL.cmake:44 (find_package_handle_standard_args)
  CMakeLists.txt:95 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find mkl (missing: MKL_LIBRARIES MKL_CORE MKL_ILP MKL_SEQ) 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.7
-- FFTW3F LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.so
-- FFTW3F STATIC LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.a
-- FFTW3F INCLUDE DIRS: /usr/include
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (fftw3f)
  does not match the name of the calling package (FFTW3F).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindFFTW3F.cmake:41 (find_package_handle_standard_args)
  CMakeLists.txt:101 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found fftw3f: /usr/lib/aarch64-linux-gnu/libfftw3f.so  
-- FFT_LIBRARIES: /usr/lib/aarch64-linux-gnu/libfftw3f.so
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (Polarssl).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:59 (find_package_handle_standard_args)
  cmake/modules/FindPolarssl.cmake:8 (INCLUDE)
  CMakeLists.txt:115 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'polarssl'
--   No package 'polarssl' found
-- POLARSSL LIBRARIES: POLARSSL_LIBRARIES-NOTFOUND
-- POLARSSL STATIC LIBRARIES: POLARSSL_STATIC_LIBRARIES-NOTFOUND
-- POLARSSL INCLUDE DIRS: POLARSSL_INCLUDE_DIRS-NOTFOUND
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (POLARSSL)
  does not match the name of the calling package (Polarssl).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindPolarssl.cmake:52 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:115 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find POLARSSL (missing: POLARSSL_LIBRARIES POLARSSL_INCLUDE_DIRS) 
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (MbedTLS).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:59 (find_package_handle_standard_args)
  cmake/modules/FindMbedTLS.cmake:8 (INCLUDE)
  CMakeLists.txt:125 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'mbedtls'
--   No package 'mbedtls' found
-- MBEDTLS LIBRARIES: /usr/lib/aarch64-linux-gnu/libmbedcrypto.so
-- MBEDTLS STATIC LIBRARIES: /usr/lib/aarch64-linux-gnu/libmbedcrypto.a
-- MBEDTLS INCLUDE DIRS: /usr/include
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (MBEDTLS)
  does not match the name of the calling package (MbedTLS).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindMbedTLS.cmake:53 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:125 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found MBEDTLS: /usr/lib/aarch64-linux-gnu/libmbedcrypto.so  
-- Checking for module 'libpcsclite'
--   No package 'libpcsclite' found
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (PCSCLITE)
  does not match the name of the calling package (PCSCLite).  This can lead
  to problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/modules/FindPCSCLite.cmake:36 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:141 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PCSCLITE (missing: PCSCLITE_LIBRARY PCSCLITE_INCLUDE_DIR) 
-- PCSC LIBRARIES: PCSCLITE_LIBRARY-NOTFOUND
-- PCSC INCLUDE DIRS: PCSCLITE_INCLUDE_DIR-NOTFOUND
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (UHD).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:59 (find_package_handle_standard_args)
  cmake/modules/FindUHD.cmake:1 (INCLUDE)
  CMakeLists.txt:153 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- UHD LIBRARIES UHD_LIBRARIES-NOTFOUND
-- UHD INCLUDE DIRS UHD_INCLUDE_DIRS-NOTFOUND
-- Could NOT find UHD (missing: UHD_LIBRARIES UHD_INCLUDE_DIRS) 
-- Checking for module 'libbladeRF'
--   No package 'libbladeRF' found
-- libbladeRF not found.
-- FINDING SOAPY.
-- Checking for module 'SoapySDR'
--   Found SoapySDR, version 0.7.1
-- Found libSOAPYSDR: /usr/include/SoapySDR, /usr/local/lib/libSoapySDR.so
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.35") found components: program_options 
-- SRSGUI LIBRARIES /usr/local/lib/libsrsgui.so
-- SRSGUI INCLUDE DIRS /usr/local/include
-- Found SRSGUI: /usr/local/lib/libsrsgui.so  
-- Performing Test HAVE_SSE
-- Performing Test HAVE_SSE - Failed
-- Performing Test HAVE_AVX
-- Performing Test HAVE_AVX - Failed
-- Performing Test HAVE_AVX2
-- Performing Test HAVE_AVX2 - Failed
-- Performing Test HAVE_FMA
-- Performing Test HAVE_FMA - Failed
-- Performing Test HAVE_AVX512
-- Performing Test HAVE_AVX512 - Failed
-- Performing Test HAVE_ERROR_INCOMPATIBLE
-- Performing Test HAVE_ERROR_INCOMPATIBLE - Failed
-- Detected ARM processor
-- Performing Test HAVE_VISIBILITY_HIDDEN
-- Performing Test HAVE_VISIBILITY_HIDDEN - Failed
-- CMAKE_C_FLAGS is  -Wall -Wno-comment -Wno-write-strings -Winline -Wno-unused-result -Wformat -Wmissing-field-initializers -Wtype-limits -std=c99 -D_GNU_SOURCE -O3 -fno-trapping-math -fno-math-errno -DBUILD_TYPE_RELEASE -DIS_ARM -DHAVE_NEON
-- CMAKE_CXX_FLAGS is  -Wall -Wno-comment -Wno-reorder -Wno-unused-but-set-variable -Wno-unused-variable -Wformat -Wmissing-field-initializers -Wtype-limits -std=c++03 -O3 -fno-trapping-math -fno-math-errno -DBUILD_TYPE_RELEASE -DIS_ARM
-- Using install prefix: /usr/local
-- Building for version: 18.12.0
--    examples will be installed.
-- No post-build command defined
-- Building with srsUE
-- No post-build-UE command defined
-- No post-build command defined
-- Building with srsENB
-- Found LibConfig++: /usr/lib/aarch64-linux-gnu/libconfig++.so
-- static LibConfig++ path: /usr/lib/aarch64-linux-gnu/libconfig++.a
-- Found LibConfig: /usr/lib/aarch64-linux-gnu/libconfig.so
-- static LibConfig path: /usr/lib/aarch64-linux-gnu/libconfig.a
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (SCTP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:59 (find_package_handle_standard_args)
  cmake/modules/FindSCTP.cmake:8 (INCLUDE)
  srsenb/CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'sctp'
--   No package 'sctp' found
-- SCTP LIBRARIES: /usr/local/lib/libsctp.so
-- SCTP INCLUDE DIRS: /usr/local/include
-- Found SCTP: /usr/local/lib/libsctp.so  
-- No post-build-ENB command defined
-- Building with srsEPC
-- Found LibConfig++: /usr/lib/aarch64-linux-gnu/libconfig++.so
-- static LibConfig++ path: /usr/lib/aarch64-linux-gnu/libconfig++.a
-- Found LibConfig: /usr/lib/aarch64-linux-gnu/libconfig.so
-- static LibConfig path: /usr/lib/aarch64-linux-gnu/libconfig.a
CMake Warning (dev) at /usr/local/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:273 (message):
  The package name passed to `find_package_handle_standard_args` (PkgConfig)
  does not match the name of the calling package (SCTP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.18/Modules/FindPkgConfig.cmake:59 (find_package_handle_standard_args)
  cmake/modules/FindSCTP.cmake:8 (INCLUDE)
  srsepc/CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Checking for module 'sctp'
--   No package 'sctp' found
-- SCTP LIBRARIES: /usr/local/lib/libsctp.so
-- SCTP INCLUDE DIRS: /usr/local/include
-- No post-build-EPC command defined
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nvidia/srsLTE1812/build

**Comment by andrepuschmann** [comment]
SCTP support isn't compiled in or available as module in your default kernel. Add it and recompile. Thanks
