### ISSUE TITLE
USRP B210  Error opening UHD code 44 in release_20_04

### ISSUE THREAD

**Issue by tomchean** [srsLTE/srsLTE#532]
## When update srsLTE from release_19_12 to release_20_04, the UHD fails ##

When I use release_19_12, everything works well, however when I update to release_20_04, UHD return error code 44. 
and I note that the UHD driver version used is different in these two release, in release_19_12 is UHD_3.14.1.1-release, and in release_20_04 it shows UHD_003.010.003.000-0-unknown, I wonder which one is correct, and how can I specify the driver when run srsenb ?

## Setup Details ##
OS : Ubuntu-18.04 + USRPB210

## Additional Information ##
release_20_04 snapshot 

![image](https://user-images.githubusercontent.com/29176881/89872502-9f062900-dbeb-11ea-967d-4ba5e3ec47b1.png)

release_19_12 snapshot 
![image](https://user-images.githubusercontent.com/29176881/89872485-94e42a80-dbeb-11ea-948d-78b943a2c908.png)

**Comment by frankist** [comment]
Try using the LTS versions of the UHD. Either 3.9 or 3.15

**Comment by tomchean** [comment]
I solve it after upgrade HUD to 3.15, thanks.

**Comment by andrepuschmann** [comment]
Great. Thanks for the feedback.

**Comment by matthew-william-lock** [comment]
How do you specify the UHD version?

**Comment by tomchean** [comment]
you can see CmakeCache to see where's the path of UHD library.
