### ISSUE TITLE
SYNC:  Found PSS but could not decode MIB

### ISSUE THREAD

**Issue by esraltun** [srsLTE/srsLTE#535]
Hi, I'm working with srsLTE(commit:30ae2226c1b1ba2fe721e10f6914ddff7ce59830) on zcu102. srsEPC -srsENB are run on zcu102 and srsUE is run on USRP 
Normally, UE does not decode PBCH, when I run srsLTE default configuration. However, I changed " time_adv_nsamples" variable as zero into enb.conf, so UE found cell, but it could not decode MIB.
I'm newbie about srsLTE. I want to learn the reason of this problem

## Setup Details ##
I'm using ad9361  as a RF front-end, libiio, libad9361 as libraries, SoapyPlutoSDR as SoapySDR module.

I added log files.
Thanks,

[ue.log](https://github.com/srsLTE/srsLTE/files/5102636/ue.log)
Esra.

**Comment by andrepuschmann** [comment]
Hey Esra, we don't support the ZCU with the public release. Note that the RF driver doesn't have timestamp support so your transmissions are likely off, and, hence, your decoding fails.
