### ISSUE TITLE
srsLTE can not install

### ISSUE THREAD

**Issue by rembulan** [srsLTE/srsLTE#541]
I get error when try to install srsLTE 20.04.1 with soapy ver 1.0

Scanning dependencies of target srslte_rf
[ 47%] Building C object lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_soapy_imp.c.o
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:25:3: error: conflicting types for ‘SoapySDRRange’
 } SoapySDRRange;
   ^~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:25:3: note: previous declaration of ‘SoapySDRRange’ was here
 } SoapySDRRange;
   ^~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:33:3: error: conflicting types for ‘SoapySDRKwargs’
 } SoapySDRKwargs;
   ^~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:33:3: note: previous declaration of ‘SoapySDRKwargs’ was here
 } SoapySDRKwargs;
   ^~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:39:30: error: conflicting types for ‘SoapySDRKwargs_fromString’
 SOAPY_SDR_API SoapySDRKwargs SoapySDRKwargs_fromString(const char *markup);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:39:30: note: previous declaration of ‘SoapySDRKwargs_fromString’ was here
 SOAPY_SDR_API SoapySDRKwargs SoapySDRKwargs_fromString(const char *markup);
                              ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:45:21: error: conflicting types for ‘SoapySDRKwargs_toString’
 SOAPY_SDR_API char *SoapySDRKwargs_toString(const SoapySDRKwargs *args);
                     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:45:21: note: previous declaration of ‘SoapySDRKwargs_toString’ was here
 SOAPY_SDR_API char *SoapySDRKwargs_toString(const SoapySDRKwargs *args);
                     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:50:5: error: redeclaration of enumerator ‘SOAPY_SDR_ARG_INFO_BOOL’
     SOAPY_SDR_ARG_INFO_BOOL,
     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:50:5: note: previous definition of ‘SOAPY_SDR_ARG_INFO_BOOL’ was here
     SOAPY_SDR_ARG_INFO_BOOL,
     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:51:5: error: redeclaration of enumerator ‘SOAPY_SDR_ARG_INFO_INT’
     SOAPY_SDR_ARG_INFO_INT,
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:51:5: note: previous definition of ‘SOAPY_SDR_ARG_INFO_INT’ was here
     SOAPY_SDR_ARG_INFO_INT,
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:52:5: error: redeclaration of enumerator ‘SOAPY_SDR_ARG_INFO_FLOAT’
     SOAPY_SDR_ARG_INFO_FLOAT,
     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:52:5: note: previous definition of ‘SOAPY_SDR_ARG_INFO_FLOAT’ was here
     SOAPY_SDR_ARG_INFO_FLOAT,
     ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:53:5: error: redeclaration of enumerator ‘SOAPY_SDR_ARG_INFO_STRING’
     SOAPY_SDR_ARG_INFO_STRING
     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:53:5: note: previous definition of ‘SOAPY_SDR_ARG_INFO_STRING’ was here
     SOAPY_SDR_ARG_INFO_STRING
     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:54:3: error: conflicting types for ‘SoapySDRArgInfoType’
 } SoapySDRArgInfoType;
   ^~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:54:3: note: previous declaration of ‘SoapySDRArgInfoType’ was here
 } SoapySDRArgInfoType;
   ^~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:103:3: error: conflicting types for ‘SoapySDRArgInfo’
 } SoapySDRArgInfo;
   ^~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:103:3: note: previous declaration of ‘SoapySDRArgInfo’ was here
 } SoapySDRArgInfo;
   ^~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:114:20: error: conflicting types for ‘SoapySDRKwargs_set’
 SOAPY_SDR_API void SoapySDRKwargs_set(SoapySDRKwargs *args, const char *key, const char *val);
                    ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:120:19: note: previous declaration of ‘SoapySDRKwargs_set’ was here
 SOAPY_SDR_API int SoapySDRKwargs_set(SoapySDRKwargs *args, const char *key, const char *val);
                   ^~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:120:27: error: conflicting types for ‘SoapySDRKwargs_get’
 SOAPY_SDR_API const char *SoapySDRKwargs_get(SoapySDRKwargs *args, const char *key);
                           ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:126:27: note: previous declaration of ‘SoapySDRKwargs_get’ was here
 SOAPY_SDR_API const char *SoapySDRKwargs_get(const SoapySDRKwargs *args, const char *key);
                           ^~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:126:20: error: conflicting types for ‘SoapySDRKwargs_clear’
 SOAPY_SDR_API void SoapySDRKwargs_clear(SoapySDRKwargs *args);
                    ^~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:132:20: note: previous declaration of ‘SoapySDRKwargs_clear’ was here
 SOAPY_SDR_API void SoapySDRKwargs_clear(SoapySDRKwargs *args);
                    ^~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:132:20: error: conflicting types for ‘SoapySDRKwargsList_clear’
 SOAPY_SDR_API void SoapySDRKwargsList_clear(SoapySDRKwargs *args, const size_t length);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:138:20: note: previous declaration of ‘SoapySDRKwargsList_clear’ was here
 SOAPY_SDR_API void SoapySDRKwargsList_clear(SoapySDRKwargs *args, const size_t length);
                    ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:138:20: error: conflicting types for ‘SoapySDRArgInfo_clear’
 SOAPY_SDR_API void SoapySDRArgInfo_clear(SoapySDRArgInfo *info);
                    ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:144:20: note: previous declaration of ‘SoapySDRArgInfo_clear’ was here
 SOAPY_SDR_API void SoapySDRArgInfo_clear(SoapySDRArgInfo *info);
                    ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:36:0:
/usr/include/SoapySDR/Types.h:144:20: error: conflicting types for ‘SoapySDRArgInfoList_clear’
 SOAPY_SDR_API void SoapySDRArgInfoList_clear(SoapySDRArgInfo *info, const size_t length);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/SoapySDR/Device.h:18:0,
                 from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:
/usr/local/include/SoapySDR/Types.h:150:20: note: previous declaration of ‘SoapySDRArgInfoList_clear’ was here
 SOAPY_SDR_API void SoapySDRArgInfoList_clear(SoapySDRArgInfo *info, const size_t length);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c: In function ‘rf_soapy_open_multi’:
/home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:289:32: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
   SoapySDRKwargs* soapy_args = SoapySDRDevice_enumerate(NULL, &length);
                                ^~~~~~~~~~~~~~~~~~~~~~~~
/home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:332:45: error: passing argument 1 of ‘SoapySDRDevice_make’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   SoapySDRDevice* sdr = SoapySDRDevice_make(&(soapy_args[dev_id]));
                                             ^
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:0:
/usr/local/include/SoapySDR/Device.h:78:31: note: expected ‘const SoapySDRKwargs * {aka const struct <anonymous> *}’ but argument is of type ‘SoapySDRKwargs * {aka struct <anonymous> *}’
 SOAPY_SDR_API SoapySDRDevice *SoapySDRDevice_make(const SoapySDRKwargs *args);
                               ^~~~~~~~~~~~~~~~~~~
/home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:370:36: error: passing argument 7 of ‘SoapySDRDevice_setupStream’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                                    &stream_args) != 0) {
                                    ^
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:0:
/usr/local/include/SoapySDR/Device.h:294:19: note: expected ‘const SoapySDRKwargs * {aka const struct <anonymous> *}’ but argument is of type ‘SoapySDRKwargs * {aka struct <anonymous> *}’
 SOAPY_SDR_API int SoapySDRDevice_setupStream(SoapySDRDevice *device,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:398:36: error: passing argument 7 of ‘SoapySDRDevice_setupStream’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                                    &stream_args) != 0) {
                                    ^
In file included from /home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:31:0:
/usr/local/include/SoapySDR/Device.h:294:19: note: expected ‘const SoapySDRKwargs * {aka const struct <anonymous> *}’ but argument is of type ‘SoapySDRKwargs * {aka struct <anonymous> *}’
 SOAPY_SDR_API int SoapySDRDevice_setupStream(SoapySDRDevice *device,
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:433:31: error: invalid initializer
   SoapySDRRange tx_range    = SoapySDRDevice_getGainRange(handler->device, SOAPY_SDR_TX, 0);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/theboel/srsLTE/lib/src/phy/rf/rf_soapy_imp.c:434:31: error: invalid initializer
   SoapySDRRange rx_range    = SoapySDRDevice_getGainRange(handler->device, SOAPY_SDR_RX, 0);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
lib/src/phy/rf/CMakeFiles/srslte_rf.dir/build.make:86: recipe for target 'lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_soapy_imp.c.o' failed
make[2]: *** [lib/src/phy/rf/CMakeFiles/srslte_rf.dir/rf_soapy_imp.c.o] Error 1
CMakeFiles/Makefile2:3854: recipe for target 'lib/src/phy/rf/CMakeFiles/srslte_rf.dir/all' failed
make[1]: *** [lib/src/phy/rf/CMakeFiles/srslte_rf.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by andrepuschmann** [comment]
What version of srsLTE and Soapy? Please use the issue template and fill all relevant fields, otherwise your questions cannot be answered.

**Comment by andrepuschmann** [comment]
Closing issue as requested information was not provided.
