### ISSUE TITLE
I installed and run srslte but it not connecting to my phone ? Why ? 

### ISSUE THREAD

**Issue by muratoznn** [srsLTE/srsLTE#542]
I installed srslte I opened srsepc and srsenb but my phone dont connecting to srslte ? Why ? This is my screen pictures .   
![Ekran görüntüsü 2020-09-02 23-40-25](https://user-images.githubusercontent.com/44745617/92037008-c9c24800-ed79-11ea-9b73-0640f875f3fd.png)
![Ekran görüntüsü 2020-09-02 23-40-33](https://user-images.githubusercontent.com/44745617/92037012-caf37500-ed79-11ea-8595-5aa9e120495d.png)

**Comment by suttonpd** [comment]
Please use the issues template to provide more information.

**Comment by andrepuschmann** [comment]
Closing the issue since requested information was not provided.
