### ISSUE TITLE
Make test failed at "network_utils_test"

### ISSUE THREAD

**Issue by pengnist** [srsLTE/srsLTE#548]
## Issue Description ##
While running make test, it returned with "network_utils_test (failed)". But I was still able to install srsLTE. 

## Setup Details ##
I followed the installation guideline

## Expected Behavior ##
Pass all the tests

## Actual Behaviour ##
"network_utils_test" failed
## Steps to reproduce the problem ##
Just follow the installation guideline.

**Comment by andrepuschmann** [comment]
No setup details provided by author. Closing issue.
