### ISSUE TITLE
other software installation before installing srsLTE

### ISSUE THREAD

**Issue by jin-github1002** [srsLTE/srsLTE#549]
Hi team
I found this instruction on the web site of srsLTE:
sudo add-apt-repository ppa:srslte/releases
sudo apt-get update
sudo apt-get install srslte -y

I am confusing that if I use this command,  do I need to install SoapySDR( I use it to connect LimeSDR USB) indenpently? I found when I use above command , soapy was installed.(version 0.6)  

In another word I want to confirm if what I need to do is as follows when I use above command.
1) install from the repository: use above command.
2) install from source: install dependency, download source code, compile and install srsLTE.

**Comment by andrepuschmann** [comment]
Hey, I am afraid in order to use the Lime, you have to install from source. This is because our binary releases aren't including Soapy bindings.
Thanks
