### ISSUE TITLE
#pragma message "Compiling without srsGUI support"

### ISSUE THREAD

**Issue by matthew-william-lock** [srsLTE/srsLTE#557]
Hi all !

I would like to show live data from my USRP while running the srsLTE package. A suggestion for how to do this is provided [here](http://www.softwareradiosystems.com/pipermail/srslte-users/2019-May/002581.html). I have tried running:
```
sudo ./srsenb --gui.enable=true
```
and changing the config files to enable it.

The following error is produced when running:
> Trying to start a plot but plots are disabled (ENABLE_GUI constant in sf_worker.cc)

I also had the following message when building srsLTE:
> /home/srslte/srsLTE/srsue/src/phy/sf_worker.cc:52:17: note: #pragma message: Compiling without srsGUI support
 #pragma message "Compiling without srsGUI support"

I am running release 20.04.2

**Comment by andrepuschmann** [comment]
Hey Matt, you also need to install srsGUI (https://github.com/srsLTE/srsGUI). It's an optional dependency and CMake will pick it up if it is installed correctly. The messages will disappear then.
