### ISSUE TITLE
Send to invalid argument

### ISSUE THREAD

**Issue by tomchean** [srsLTE/srsLTE#579]
#347  Issue Description ##
When I run epc and enb at same machine, everything works well, but when I run epc at different host, I can successfully initialize sctp, but after UE connected, srsenb show "send to : invalid argument", I am not sure if the config file is wrong.

enb host's ip is 192.168.50.8
epc host's ip is 192.168.50.180

and  my enb.conf looks like following
[enb]
mme_addr = 192.168.50.180
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 192.168.50.8
n_prb = 50

![image](https://user-images.githubusercontent.com/29176881/97412617-bfb56380-193c-11eb-9ca4-21a37822e225.png)

**Comment by herlesupreeth** [comment]
I believe `gtp_bind_addr = 127.0.1.1` should be set to 192.168.50.8 as well

**Comment by tomchean** [comment]
Really thanks, I fix it by setting  gtp_bind_addr = 192.168.50.8
