### ISSUE TITLE
How to enable QAM256 in downlink eNb?

### ISSUE THREAD

**Issue by CassianoDev** [srsLTE/srsLTE#583]
## Issue Description ##
Smartphone does not work at 256 QAM in the downlink.

## Setup Details ##
LimeSDR USB 3.0, srsLTE 20.04, PC Core i74790, 32GBRAM, smartphone Xiaomi Note8 MIUI11.

## Expected Behavior ##
Up 256QAM in Downlink and 64QAM in Uplink.

## Actual Behaviour ##
Only 64QAM works in Downlink, i tried some settings but to no avail!

## Steps to reproduce the problem ##
Up srsLTE on LimeSDR and connect Smartphone note8 xiaomi!

## Additional Information ##
None.

I've tried a few things but I can't!
is this possible?
is here 64QAM and 16QAM up only!

I tried some things to no avail!...

**Comment by andrepuschmann** [comment]
If you file an issue, please use the issue template and provide all relevant info. That's what it is there for. In this example, what phone are you using? Does it have QAM256 support?

**Comment by CassianoDev** [comment]
> If you file an issue, please use the issue template and provide all relevant info. That's what it is there for. In this example, what phone are you using? Does it have QAM256 support?

Sorry I was in a hurry!
edited!

My phone is Xiaomi Note8

**Comment by andrepuschmann** [comment]
> > If you file an issue, please use the issue template and provide all relevant info. That's what it is there for. In this example, what phone are you using? Does it have QAM256 support?
> 
> Sorry I was in a hurry!
> edited!
> 
> My phone is Xiaomi Note8, is supported 256QAM!

Again, please follow the issue template. Send a eNB PCAP and a log in info if possible.

**Comment by CassianoDev** [comment]
> > > If you file an issue, please use the issue template and provide all relevant info. That's what it is there for. In this example, what phone are you using? Does it have QAM256 support?
> > 
> > 
> > Sorry I was in a hurry!
> > edited!
> > My phone is Xiaomi Note8, is supported 256QAM!
> 
> Again, please follow the issue template. Send a eNB PCAP and a log in info if possible.

Ok, thanks!

Files log and pcap annexed

**Comment by CassianoDev** [comment]
> > > > If you file an issue, please use the issue template and provide all relevant info. That's what it is there for. In this example, what phone are you using? Does it have QAM256 support?
> > > 
> > > 
> > > Sorry I was in a hurry!
> > > edited!
> > > My phone is Xiaomi Note8, is supported 256QAM!
> > 
> > 
> > Again, please follow the issue template. Send a eNB PCAP and a log in info if possible.
> 
> Ok, thanks!
> 
> Files log and pcap annexed

[enb.log](https://github.com/srsLTE/srsLTE/files/5474708/enb.log)

[pcap.zip](https://github.com/srsLTE/srsLTE/files/5474712/pcap.zip)

**Comment by CassianoDev** [comment]
> > > > > If you file an issue, please use the issue template and provide all relevant info. That's what it is there for. In this example, what phone are you using? Does it have QAM256 support?
> > > > 
> > > > 
> > > > Sorry I was in a hurry!
> > > > edited!
> > > > My phone is Xiaomi Note8, is supported 256QAM!
> > > 
> > > 
> > > Again, please follow the issue template. Send a eNB PCAP and a log in info if possible.
> > 
> > 
> > Ok, thanks!
> > Files log and pcap annexed
> 
> [enb.log](https://github.com/srsLTE/srsLTE/files/5474708/enb.log)
> 
> [pcap.zip](https://github.com/srsLTE/srsLTE/files/5474712/pcap.zip)

**Comment by andrepuschmann** [comment]
Thanks for the logs, we investigate.

**Comment by CassianoDev** [comment]
> Thanks for the logs, we investigate.

Thank you so much for your help!

After fine uplink adjustments, LimeSDR USB is up 48h+ 2x2@10.

**Comment by cbalint13** [comment]
> > Thanks for the logs, we investigate.
> 
> Thank you so much for your help!
> 
> After fine uplink adjustments, LimeSDR USB is up 48h+ 2x2@10.

@CassianoDev ,

What do you mean by fine uplink adjusment ?

**Comment by CassianoDev** [comment]
> > > Thanks for the logs, we investigate.
> > 
> > 
> > Thank you so much for your help!
> > After fine uplink adjustments, LimeSDR USB is up 48h+ 2x2@10.
> 
> @CassianoDev ,
> 
> What do you mean by fine uplink adjusment ?

RX Gain, I was getting a lot of noise in RX (my antennas not good).

Adjust of UE PUSCH pwr for compensate the low gain and get high SNR.

Antenna height adjustment for frequency used (857 MHz) ARFCN 6400.
I don't have good experiences at high frequencies!

**Comment by CassianoDev** [comment]
> Thanks for the logs, we investigate.

Hey...
256QAM works fine for me now at 20.10!
Is it possible to use 64QAM on the uplink?

thank you!

**Comment by andrepuschmann** [comment]
> 256QAM works fine for me now at 20.10 release!

Ahhh, you tested with 20.04.2, just saw you were using `0ec49a7b1`. I didn't see that. Of course, it wasn't working with that version.

> Is it possible to use 64QAM on the uplink?

Not yet, but will be added.

Closing issue.

**Comment by joeldelosangeles** [comment]
Hi,  Is 64QAM UL now supported in the latest version 22.04?
