### ISSUE TITLE
B210 like LTE modem

### ISSUE THREAD

**Issue by utya** [srsLTE/srsLTE#592]
hello. I'm sorry for the stupid question, I wanted to know if I can use this project to make и210 in the role of a lte modem? (cleint)

**Comment by kbarlee** [comment]
Hey @utya. Yes, you can - just run srsUE.

**Comment by andrepuschmann** [comment]
Hey, just wanted to ack what @kbarlee already said. B210 works, N210 doesn't (just saying bc you are using a weird character that looks like a N to me).
