### ISSUE TITLE
Low TX Power of SCELL in Carrier Aggregation

### ISSUE THREAD

**Issue by CassianoDev** [srsLTE/srsLTE#593]
## Issue Description ##
When up the network at 2 xCA, a SCELL has a weak signal. 

## Setup Details ##
Ubuntu 20,04, Intel Core i74790, 32GBRAM, LimeSDR USB 3.0 Board v1.4
, srsLTE 20.10 commit fd5cde525 on branch master, UE: S7 EDGE g935f (exynos version)

## Expected Behavior ##
SCELL power equivalent to the primary cell.

## Actual Behaviour ##
SCELL power is low!
Primary Cell: RSRP: -92, RSRQ: -4, RSSI: -74, SINR: 33
SCELL: RSRP: -130, RSRQ: -21, SINR: -16

## Steps to reproduce the problem ##
Install soapy drivers for lms7, build last LimeSuite, configure rr.conf for:
cell_list =
(
  {
    rf_port = 0;
    cell_id = 0x01;
    tac = 0x0001;
    pci = 1;
    root_seq_idx = 204;
    dl_earfcn = 2850;

    // CA cells
    scell_list = (
      {cell_id = 0x02; cross_carrier_scheduling = false; scheduling_cell_id = 0x01; ul_allowed = true}
    )
  },
  {
    rf_port = 1;
    cell_id = 0x02;
    tac = 0x0001;
    pci = 4;
    root_seq_idx = 205;
    dl_earfcn = 3050;

    // CA cells
    scell_list = (
      {cell_id = 0x01; cross_carrier_scheduling = false; scheduling_cell_id = 0x02; ul_allowed = true}
    )
  }
Attach S7 EDGE g935f (exynos version)
run *#0011# and view radio info

## Additional Information ##
I tried to change the power by tx_power but without success!

Log All Level Info:
[log.zip](https://github.com/srsLTE/srsLTE/files/5562322/log.zip)

**Comment by andrepuschmann** [comment]
Hey, I don't think you can have two cells on different EARFCNs with a LimeSDR. It has two antenna ports, but those are for diversity (MIMO). In theory, of course, you could have a channelizer in the FPGA that allows you to have two carriers if they fall inside the total RF bandwidth. But I doubt that this is implemented. Lime guys may correct me if I am wrong.
