### ISSUE TITLE
Inter eNB mobility 

### ISSUE THREAD

**Issue by pengyuan-zhou** [srsLTE/srsLTE#596]
Hi, 
Thanks for the great work and the release of 20.10 supporting mobility is really helpful.

As also mentioned by #411 , I'm wondering if there's any plan to realize inter eNB handover in the near future?

Thank you.

**Comment by andrepuschmann** [comment]
S1 HO between two eNBs is implemented in 20.10. Please check the release notes. Also, there is a dedicated HO [appnote](https://docs.srslte.com/en/latest/app_notes/source/handover/source/index.html).

**Comment by pengyuan-zhou** [comment]
Hi Andre @andrepuschmann,

Thanks for the reply. I followed the suggested note and met with an error at the last step.
Could you kindly take a look? #599 

Thank you so much.
