### ISSUE TITLE
make test fail

### ISSUE THREAD

**Issue by fyy919** [srsLTE/srsLTE#598]
Issue Description
When building srsLTE, I execute the command make test, but log shows the error message: 
99% tests passed, 1 tests failed out of 791

Label Time Summary:
long      = 134.03 sec (253 tests)
phy       = 134.03 sec (253 tests)
srsenb    =   6.24 sec (5 tests)
srsue     =   1.02 sec (1 test)

Total Test time (real) = 245.71 sec

The following tests FAILED:
	773 - nas_test (SEGFAULT)
Errors while running CTest
Makefile:149: recipe for target 'test' failed
make: *** [test] Error 8

 Setup Details 
Operation System: Ubuntu 16.04 LTS
RF front-end: USRP B210
library and driver versions: UHD 3.15.0

Expected Behavior
make test successful

Actual Behaviour 
~/srsLTE/build$ sudo ./srsue/test/upper/nas_test

17:10:06.715511 [NAS ] [I] New state DEREGISTERED
17:10:06.715604 [NAS ] [I] DL lcid PDU
             0000: 07 52 01 0c 63 a8 54 13 e6 a4 ce d9 86 fb e5 ce 
             0010: 9b 62 5e 10 67 57 b3 c2 b9 70 90 01 0c 72 8a 67 
             0020: 57 92 52 b8 
17:10:06.715613 [NAS ] [I] DL lcid Decrypted PDU
             0000: 07 52 01 0c 63 a8 54 13 e6 a4 ce d9 86 fb e5 ce 
             0010: 9b 62 5e 10 67 57 b3 c2 b9 70 90 01 0c 72 8a 67 
             0020: 57 92 52 b8 
17:10:06.715614 [NAS ] [I] Received Authentication Request
17:10:06.715616 [NAS ] [I] MCC=61441, MNC=65281
17:10:06.715618 [NAS ] [D] Authentication request RAND
             0000: 0c 63 a8 54 13 e6 a4 ce d9 86 fb e5 ce 9b 62 5e 
17:10:06.715623 [NAS ] [D] Authentication request AUTN
             0000: 67 57 b3 c2 b9 70 90 01 0c 72 8a 67 57 92 52 b8 
17:10:06.715640 [NAS ] [I] Network authentication successful
17:10:06.715642 [NAS ] [D] Not applying security for PDU. No context configured.
17:10:06.715643 [NAS ] [I] Sending Authentication Response
17:10:06.715648 [NAS ] [I] Generated k_asme:
             0000: 8d 42 d1 bb 80 4b b4 53 cc 00 6d ed 4b 82 dd 55 
             0010: de 66 8b 2b 61 99 73 5d 2d ae 72 fa 24 70 97 ed 
17:10:06.715651 [NAS ] [I] DL lcid PDU
             0000: 37 4e fd 57 11 00 07 5d 02 01 02 f0 70 c1 
17:10:06.715654 [NAS ] [I] DL lcid Decrypted PDU
             0000: 37 4e fd 57 11 00 07 5d 02 01 02 f0 70 c1 
17:10:06.715657 [NAS ] [I] Received Security Mode Command ksi: 1, eea: EEA0, eia: 128-EIA2
17:10:06.715663 [NAS ] [I] NAS encryption key - k_nas_enc
             0000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
             0010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
17:10:06.715667 [NAS ] [I] NAS integrity key - k_nas_int
             0000: ff 79 be dd c2 b9 39 eb 0b 2f cc 30 ef 6d 00 37 
             0010: 5b ae 51 b3 c0 26 2a 09 2e 2f b3 e5 d3 bc 0f 44 
17:10:06.715669 [NAS ] [D] Generating integrity check. integ_algo:2, count_dl:0, lcid:1
17:10:06.715681 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [4e fd 57 11]
17:10:06.715687 [NAS ] [I] Sending Security Mode Complete nas_current_ctxt.tx_count=0, RB=lcid
17:10:06.739535 [NAS ] [I] New state DEREGISTERED
17:10:06.739552 [USIM] [I] Read Home PLMN Id=00101
17:10:06.739571 [NAS ] [E] Empty EIA list. Select at least one EIA algorithm.
17:10:06.739572 [NAS ] [E] Empty EEA list. Select at least one EEA algorithm.
17:10:06.739575 [NAS ] [I] Skip reading context from file.
Found PLMN:  Id=00101, TAC=65535
17:10:06.744757 [NAS ] [I] Attach Request with cause mo-Data.
17:10:06.744760 [NAS ] [I] No PLMN selected. Starting PLMN Search...
17:10:06.744763 [NAS ] [I] Found PLMN:  Id=00101, TAC=65535
NAS generated SDU (len=22):
17:10:06.744770 [NAS ] [I] Selecting Home PLMN Id=00101
[07 41 71 08 09 10 10 10 32 54 76 98 02 17:10:06.744784 [NAS ] [I] Generating attach request
17:10:06.744793 [NAS ] [I] Generating PDN Connectivity Request
17:10:06.744794 [NAS ] [D] Requesting IPv4 PDN protocol
17:10:06.744795 [NAS ] [I] Requesting IMSI attach (IMSI=001010123456789)
17:10:06.744797 [NAS ] [D] Starting T3410
17:10:06.744800 [NAS ] [I] Proc "RRC Connect" - Starting...
00 00 00 05 02 01 d0 11 d1 ];
17:10:06.744902 [NAS ] [I] Proc "RRC Connect" - Connection established correctly. Waiting for Attach
17:10:06.744907 [NAS ] [I] Proc "PLMN Search" - Starting...
17:10:06.745192 [NAS ] [E] Proc "RRC Connect" - Timeout or received attach reject while trying to attach
17:10:06.745196 [NAS ] [I] Proc "PLMN Search" - Completed with failure
17:10:06.745197 [NAS ] [D] Clearing EPS bearer context
17:10:06.745198 [NAS ] [I] New state DEREGISTERED
17:10:06.745202 [NAS ] [I] Attach Request from PLMN Search failed
Found PLMN:  Id=00101, TAC=65535
17:10:06.745281 [NAS ] [I] Attach Request with cause mo-Data.
17:10:06.745282 [NAS ] [I] No PLMN selected. Starting PLMN Search...
17:10:06.745284 [NAS ] [I] Found PLMN:  Id=00101, TAC=65535
17:10:06.745290 [NAS ] [I] Selecting Home PLMN Id=00101
17:10:06.745291 [NAS ] [I] Proc "RRC Connect" - Stopping. Reason: Already connected
17:10:06.745292 [NAS ] [I] Proc "PLMN Search" - Completed with success
17:10:06.745292 [NAS ] [I] Proc "PLMN Search" - Starting...
Attach failed (attempt 1/5)
17:10:06.745558 [NAS ] [I] Timer T3410 expired after attach attempt 1/5: starting T3411
17:10:06.745946 [NAS ] [I] Timer T3411 expired: trying to attach again
17:10:06.745960 [NAS ] [I] Generating attach request
17:10:06.745967 [NAS ] [I] Generating PDN Connectivity Request
17:10:06.745968 [NAS ] [D] Requesting IPv4 PDN protocol
17:10:06.745969 [NAS ] [I] Requesting IMSI attach (IMSI=001010123456789)
17:10:06.745970 [NAS ] [D] Starting T3410
Network attach successful. IP: 192.168.5.2
17:10:06.746043 [NAS ] [I] DL lcid PDU
             0000: 27 00 00 00 00 00 07 42 01 3e 06 00 00 f1 10 00 
             0010: 01 00 2a 52 01 c1 01 04 1b 07 74 65 73 74 31 32 
             0020: 33 06 6d 6e 63 30 30 31 06 6d 63 63 30 30 31 04 
             0030: 67 70 72 73 05 01 c0 a8 05 02 27 01 80 50 0b f6 
             0040: 00 f1 10 80 01 01 35 16 6d bc 64 01 00 
17:10:06.746048 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [00 00 00 00]
17:10:06.746054 [NAS ] [I] DL lcid Decrypted PDU
             0000: 27 00 00 00 00 00 07 42 01 3e 06 00 00 f1 10 00 
             0010: 01 00 2a 52 01 c1 01 04 1b 07 74 65 73 74 31 32 
             0020: 33 06 6d 6e 63 30 30 31 06 6d 63 63 30 30 31 04 
             0030: 67 70 72 73 05 01 c0 a8 05 02 27 01 80 50 0b f6 
             0040: 00 f1 10 80 01 01 35 16 6d bc 64 01 00 
17:10:06.746055 [NAS ] [I] Received Attach Accept
17:10:06.746056 [NAS ] [D] Stopping T3410
17:10:06.746059 [NAS ] [I] Network attach successful. APN: test123.mnc001.mcc001.gprs, IP: 192.168.5.2
17:10:06.746076 [GW  ] [I] TUN file descriptor = 4
17:10:06.746638 [GW  ] [D] Trying to obtain IPv6 addr of tun0 interface
17:10:06.746878 [GW  ] [D] NETLINK message type 20
17:10:06.746881 [GW  ] [D] NETLINK message type 20
17:10:06.746881 [GW  ] [D] NETLINK message type 20
17:10:06.746890 [GW  ] [D] Found link-local IPv6 address: fe80::ab53:ee8:d4b6:3ade
17:10:06.748157 [NAS ] [I] New state REGISTERED
17:10:06.748168 [NAS ] [D] Not applying security for PDU. No context configured.
17:10:06.748169 [NAS ] [I] Sending Attach Complete
17:10:06.748278 [GW  ] [I] GW IP packet receiver thread run_enable
17:10:06.748285 [GW  ] [D] Read 48 bytes from TUN fd=4, idx=0
17:10:06.748287 [GW  ] [D] IPv6 packet total length: 48 Bytes
17:10:06.748296 [GW  ] [I] TX PDU
             0000: 60 00 00 00 00 08 3a ff fe 80 00 00 00 00 00 00 
             0010: ab 53 0e e8 d4 b6 3a de ff 02 00 00 00 00 00 00 
             0020: 00 00 00 00 00 00 00 02 85 00 b3 66 00 00 00 00 
17:10:06.748300 [GW  ] [I] LCID=0 not active, requesting NAS attach (0/40)
17:10:06.748302 [NAS ] [I] Attach Request with cause mo-Data.
17:10:06.748303 [NAS ] [I] NAS is already registered and RRC connected
17:10:06.770807 [NAS ] [I] New state DEREGISTERED
17:10:06.770830 [NAS ] [E] Empty EIA list. Select at least one EIA algorithm.
17:10:06.770831 [NAS ] [E] Empty EEA list. Select at least one EEA algorithm.
17:10:06.770834 [NAS ] [I] Skip reading context from file.
17:10:06.770840 [NAS ] [I] DL lcid PDU
             0000: 27 00 00 00 00 00 02 5a d9 
17:10:06.770843 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [00 00 00 00]
17:10:06.770846 [NAS ] [I] DL lcid Decrypted PDU
             0000: 27 00 00 00 00 00 02 5a d9 
17:10:06.770847 [NAS ] [I] ESM information request received for beaser=0, transaction_id=90
17:10:06.770850 [NAS ] [D] Including APN srslte in ESM info response
17:10:06.770851 [NAS ] [D] Including CHAP authentication for user srsuser in ESM info response
17:10:06.770868 [NAS ] [D] Not applying security for PDU. No context configured.
17:10:06.770874 [NAS ] [I] Sending ESM information response
             0000: 02 5a da 28 07 06 73 72 73 6c 74 65 27 3f 80 c2 
             0010: 23 1c 01 00 00 1c 10 67 c6 69 73 51 ff 4a ec 29 
             0020: cd ba ab f2 fb e3 46 73 72 73 75 73 65 72 c2 23 
             0030: 1c 02 00 00 1c 10 79 c0 f7 32 67 53 02 48 c7 f1 
             0040: 87 7a 55 3c 6b d0 73 72 73 75 73 65 72 
17:10:06.782368 [NAS ] [I] New state DEREGISTERED
17:10:06.782376 [NAS ] [E] Empty EIA list. Select at least one EIA algorithm.
17:10:06.782378 [NAS ] [E] Empty EEA list. Select at least one EEA algorithm.
17:10:06.782380 [NAS ] [I] Skip reading context from file.
Network attach successful. IP: 192.168.5.2
17:10:06.782385 [NAS ] [I] DL lcid PDU
             0000: 27 00 00 00 00 00 62 00 c5 05 01 01 07 21 31 00 
             0010: 03 40 08 ae 5d 02 00 c2 81 34 01 4d 
17:10:06.782386 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [00 00 00 00]
17:10:06.782390 [NAS ] [I] DL lcid Decrypted PDU
             0000: 27 00 00 00 00 00 62 00 c5 05 01 01 07 21 31 00 
             0010: 03 40 08 ae 5d 02 00 c2 81 34 01 4d 
17:10:06.782393 [NAS ] [I] Received Activate Dedicated EPS bearer context request (eps_bearer_id=6, linked_bearer_id=5, proc_id=0)
17:10:06.782394 [NAS ] [I] Traffic Flow Template: TFT OP code 0x1, Filter list size 1, Parameter list size 0
17:10:06.782395 [NAS ] [E] No linked default EPS bearer found (5).
17:10:06.782401 [NAS ] [I] DL lcid PDU
             0000: 27 00 00 00 00 00 07 42 01 3e 06 00 00 f1 10 00 
             0010: 01 00 2a 52 01 c1 01 04 1b 07 74 65 73 74 31 32 
             0020: 33 06 6d 6e 63 30 30 31 06 6d 63 63 30 30 31 04 
             0030: 67 70 72 73 05 01 c0 a8 05 02 27 01 80 50 0b f6 
             0040: 00 f1 10 80 01 01 35 16 6d bc 64 01 00 
17:10:06.782408 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [00 00 00 00]
17:10:06.782409 [NAS ] [I] Update local count to received value 0
17:10:06.782415 [NAS ] [I] DL lcid Decrypted PDU
             0000: 27 00 00 00 00 00 07 42 01 3e 06 00 00 f1 10 00 
             0010: 01 00 2a 52 01 c1 01 04 1b 07 74 65 73 74 31 32 
             0020: 33 06 6d 6e 63 30 30 31 06 6d 63 63 30 30 31 04 
             0030: 67 70 72 73 05 01 c0 a8 05 02 27 01 80 50 0b f6 
             0040: 00 f1 10 80 01 01 35 16 6d bc 64 01 00 
17:10:06.782416 [NAS ] [I] Received Attach Accept
17:10:06.782420 [NAS ] [I] Network attach successful. APN: test123.mnc001.mcc001.gprs, IP: 192.168.5.2
17:10:06.782428 [NAS ] [I] New state REGISTERED
17:10:06.782431 [NAS ] [D] Not applying security for PDU. No context configured.
17:10:06.782432 [NAS ] [I] Sending Attach Complete
17:10:06.782437 [NAS ] [I] DL lcid PDU
             0000: 27 00 00 00 00 00 62 00 c5 05 01 01 07 21 31 00 
             0010: 03 40 08 ae 5d 02 00 c2 81 34 01 4d 
17:10:06.782439 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [00 00 00 00]
17:10:06.782441 [NAS ] [I] Update local count to received value 0
17:10:06.782445 [NAS ] [I] DL lcid Decrypted PDU
             0000: 27 00 00 00 00 00 62 00 c5 05 01 01 07 21 31 00 
             0010: 03 40 08 ae 5d 02 00 c2 81 34 01 4d 
17:10:06.782446 [NAS ] [I] Received Activate Dedicated EPS bearer context request (eps_bearer_id=6, linked_bearer_id=5, proc_id=0)
17:10:06.782447 [NAS ] [I] Traffic Flow Template: TFT OP code 0x1, Filter list size 1, Parameter list size 0
17:10:06.782449 [NAS ] [D] Not applying security for PDU. No context configured.
17:10:06.782452 [NAS ] [I] Sending Activate Dedicated EPS Bearer context accept (eps_bearer_id=6, proc_id=0)
             0000: 62 00 c6 
17:10:06.782455 [NAS ] [I] DL lcid PDU
             0000: 27 00 00 00 00 00 62 00 cd 24 
17:10:06.782456 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [00 00 00 00]
17:10:06.782457 [NAS ] [I] Update local count to received value 0
17:10:06.782461 [NAS ] [I] DL lcid Decrypted PDU
             0000: 27 00 00 00 00 00 62 00 cd 24 
17:10:06.782462 [NAS ] [I] Received Deactivate EPS bearer context request (eps_bearer_id=6, proc_id=0, cause=0x24)
17:10:06.782466 [NAS ] [I] Removed EPS bearer context (eps_bearer_id=6)
17:10:06.782468 [NAS ] [D] Not applying security for PDU. No context configured.
17:10:06.782470 [NAS ] [I] Sending Deactivate EPS Bearer context accept (eps_bearer_id=6, proc_id=0)
             0000: 62 00 ce 
17:10:06.782474 [NAS ] [I] DL lcid PDU
             0000: 27 00 00 00 00 00 62 00 cd 24 
17:10:06.782479 [NAS ] [I] Integrity check ok. Local: count=0, Received: count=0  [00 00 00 00]
17:10:06.782480 [NAS ] [I] Update local count to received value 0
17:10:06.782485 [NAS ] [I] DL lcid Decrypted PDU
             0000: 27 00 00 00 00 00 62 00 cd 24 
17:10:06.782486 [NAS ] [I] Received Deactivate EPS bearer context request (eps_bearer_id=6, proc_id=0, cause=0x24)
17:10:06.782486 [NAS ] [E] EPS bearer doesn't exist (eps_bearer_id=6)
nas_test: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Aborted (core dumped)

**Comment by andrepuschmann** [comment]
Hey, this issue is a race between two threads in the testing code. We've seen this regression internally as well. Could you give https://github.com/srsLTE/srsLTE/tree/nas_test_fix a try to see if that fixes it for you? In any case, the failing test shouldn't impact the NAS functionality at all.

**Comment by fyy919** [comment]
Thanks for your reply!
I have solved this issue.
发件人: Andre Puschmann
发送时间: 2020年11月26日 16:54
收件人: srsLTE/srsLTE
抄送: fyy919; Author
主题: Re: [srsLTE/srsLTE] make test fail (#598)

Hey, this issue is a race between two threads in the testing code. We've seen this regression internally as well. Could you give https://github.com/srsLTE/srsLTE/tree/nas_test_fix a try to see if that fixes it for you? In any case, the failing test shouldn't impact the NAS functionality at all.

**Comment by andrepuschmann** [comment]
Ok, good. The fix is part of the next release.
