### ISSUE TITLE
[Bug] 20% PDCCH-Miss with USRP B210

### ISSUE THREAD

**Issue by jmmlmendes** [srsLTE/srsLTE#60]
The pdsch_enodeb/pdsch_ue examples always report 20% of PDCCH misses using the most recent release (release_001_003_000), the last version of master (ed35015ff59) and the next branch (17d5ebca7ede).
Meanwhile, this does not happen using release_001_002_000.

To reproduce, simply run the pdsch_enodeb example in one machine with an USRP B210 and the pdsch_ue example in another machine/USRP, the number of PRBs/MCS does not matter much, it is observable with all values.

What strikes me as relevant is the fact that the number is always 20% (except at higher number of PRBs/MCS when it's higher as expected - can't decode fast enough).

Did you came across this issue in the past?

**Comment by baharxy** [comment]
I have  encountered  the exact same issue (with the latest issue, the miss always 20%), did you find out why is this happening?

**Comment by jmmlmendes** [comment]
Didn't look further into it but since other people can reproduce it (i.e. likely not my setup's fault), I'll take a deeper look and report the findings.

**Comment by andrepuschmann** [comment]
Just tested with the current master and the issue doesn't seem to be there anymore. Please file a bug report again should the issue still be present for you with the latest version.
