### ISSUE TITLE
gNB Not Initializing

### ISSUE THREAD

**Issue by MichaelFay** [srsLTE/srsLTE#602]
## Issue Description ##
5G NR gNB does not initialize Ettus B200

## Setup Details ##
Docker Bridge Network, Ubuntu 18.04 LTS, NI B200, B200 RF Front-end, UHD 3.15.lts

* We have the standard LTE eNB, EPC successfully working through docker

## Expected Behavior ##
gNB to bring up and UHD device to be initialized

## Actual Behaviour ##
B200 Does not bring-up. No errors seem to be thrown.  

## Steps to reproduce the problem ##
Configuration files should be attached
[configs.zip](https://github.com/srsLTE/srsLTE/files/5656935/configs.zip)

**Comment by andrepuschmann** [comment]
Hi Michael, the gNB stack in the srsLTE 20.10 release is very limited and has only some initial layer 2 functionality implemented. As a consequence no USRP or any other RF hardware is used. We will significantly update the 5G functionality with the upcoming releases of srsLTE, beginning with a NSA UE in the next release. Stay tuned.
