### ISSUE TITLE
Where is the TAC in enb.conf

### ISSUE THREAD

**Issue by caleb18719516** [srsLTE/srsLTE#619]
## Issue Description ##
I want to modify the enb.conf to let the srsenb connect to another Core network(not srsepc)
one step is change the TAC to match with corenetwork
but I can't find the TAC in enb.conf
######### my enb.conf is like this #############
[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
mme_addr = 127.0.1.100
gtp_bind_addr = 127.0.1.1
s1c_bind_addr = 127.0.1.1
n_prb = 50
#tm = 4
#nof_ports = 2
#############################
Is anyone know how to set the TAC?
please help me,thanks very much
may god bless you all

**Comment by andrepuschmann** [comment]
Hey, the TAC used to be in `enb.conf` but has been moved to `rr.conf` recently after adding multi-cell support. Note that each cell of a eNB could have another TAC. See `rr.conf.example` in the srsenb folder.
