### ISSUE TITLE
srsenb and srseu crased

### ISSUE THREAD

**Issue by mac-435** [srsLTE/srsLTE#628]
**Issue Description**
srsenb and srseu at exist (crashed)
**Setup Details**
Ubuntu 18.04.3, Sdr Ettus X310
**Expected Behavior**
correct execution of the program
**Actual Behaviour**
--- command='srsenb' version=20.10.1 signal=11 date='11/02/2021 23:39:51' ---
	srsenb(+0x19463f) [0x5600ea16363f]
	/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7ff32d315210]
	/usr/local/lib/libsrslte_rf.so.0(+0x2e3cd) [0x7ff32da4c3cd]
	/usr/local/lib/libsrslte_rf.so.0(rf_uhd_open_multi+0x94e) [0x7ff32da329ae]
	/usr/local/lib/libsrslte_rf.so.0(srslte_rf_open_devname+0x6d) [0x7ff32da2e00d]
	srsenb(+0x2ae85e) [0x5600ea27d85e]
	srsenb(+0x2b123c) [0x5600ea28023c]
	srsenb(+0x84330) [0x5600ea053330]
	srsenb(+0x6a800) [0x5600ea039800]
	/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ff32d2f60b3]
	srsenb(_start+0x2e) [0x5600ea03a72e]
**Steps to reproduce the problem**
Unexpected exit

**Comment by andrepuschmann** [comment]
I am afraid it's not possible to tell what's going on here. I suggest you try with the new release and report back if the issue still persists. THanks
