### ISSUE TITLE
epc doesn't start due to the following issue 

### ISSUE THREAD

**Issue by saichandrad** [srsLTE/srsLTE#631]
## Issue Description ##
When I try to start the epc using srsepc command - It shows it couldn't initialize SGi-interface, SPGW-GTP-U, SPGW

## Setup Details ##
Running on ubuntu 16

## Expected Behavior ##
epc start

## Actual Behaviour ##
shows it couldn't initializae - SGi-interface, SPGW-GTP-U, SPGW

## Steps to reproduce the problem ##
run sudo srsepc commnd

![image](https://user-images.githubusercontent.com/70608707/110359611-b08da300-800b-11eb-8d4b-476b69eed2c5.png)

**Comment by JayakumarCK2** [comment]
I think you have a suspended srsepc.
Do pidof srsepc : you will get a Jobid
Kill the process, restart epc

**Comment by matan1008** [comment]
In my humble opinion you are missing the `sudo` before the `srsepc` command, thus failing to create the TUN device.

**Comment by liumaolin-931** [comment]
Hi
I have some similar problems and the terminal interface is as follows:

sudo srsepc epc.conf
Built in Release mode using commit 45486b6e2 on branch master.

---  Software Radio Systems EPC  ---

Reading configuration file epc.conf...
HSS Initialized.
Error binding SCTP socket
Error initializing GTP-C

The strange thing is that it can work normally after boot and restart, but when I turn off the current terminal and open a new one, this error will appear. Can someone help me?Thanks!

**Comment by andrepuschmann** [comment]
probably another EPC running using the same port.

**Comment by EhsaanIlyas456** [comment]
anyone solved it?

**Comment by KingEverest** [comment]
the problem occurs when you run "srsran_install_configs.sh user" without root provilege. To solve the problem run the script with root privileges like as below

'sudo srsran_install_configs.sh user'
