### ISSUE TITLE
make error in rf_zmq_imp.c

### ISSUE THREAD

**Issue by black-pigeon** [srsLTE/srsLTE#635]
Hello,I build this project from source followed by the build Instructions.But When I use the make command,the error occured. What should I do to slove this problem. By the way, I used to do the same thing on my another virtual machine, and that virtual machine don't have this problem.
![Screenshot from 2021-03-23 14-44-20](https://user-images.githubusercontent.com/51851650/112104608-63eac000-8be6-11eb-804f-58f3a11703e0.png)

**Comment by andrepuschmann** [comment]
Seems your missing some header files or have a version conflict. What OS is it? What library versions? Unless you provide all that nobody can help you. Closing the issue.
