### ISSUE TITLE
Unable to search the network on the phone

### ISSUE THREAD

**Issue by Darcy0221** [srsLTE/srsLTE#637]
## Issue Description ##
[Describe the issue in detail 
Hello, I try running srsEnb with B210  on Ubuntu 18.04.
I`m new to lte, so I just used default configs made by srslte_install_configs.sh user
SrsEpc and srsenb start ok，but I can’t search the internet with my phone.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

Built in Release mode using 20.10.1.

---  Software Radio Systems EPC  ---

Reading configuration file epc.conf...
HSS Initialized.
MME S11 Initialized
MME GTP-C Initialized
MME Initialized. MCC: 0xf001, MNC: 0xff01
SPGW GTP-U Initialized.
SPGW S11 Initialized.
SP-GW Initialized.
Received S1 Setup Request.
S1 Setup Request - eNB Name: srsenb01, eNB id: 0x19b
S1 Setup Request - MCC:001, MNC:01
S1 Setup Request - TAC 7, B-PLMN 0xf110
S1 Setup Request - Paging DRX v128
Sending S1 Setup Response

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file enb.conf...
WARNING: Could not verify cpu0 scaling governor
WARNING: Could not verify cpu1 scaling governor
WARNING: Could not verify cpu2 scaling governor
WARNING: Could not verify cpu3 scaling governor

Built in Release mode using 20.10.1.

Opening 1 channels in RF device=default with args=default
[INFO] [UHD] linux; GNU C++ version 7.5.0; Boost_106501; UHD_3.14.0.0-0-unknown
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 2.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Setting frequency: DL=2680.0 Mhz, UL=2560.0 MHz for cc_idx=0

==== eNodeB started ===
Type <t> to view trace

## Expected Behavior ##
[What you expect to happen]

My phone can search the network and connect

## Actual Behaviour ##
[What happens instead e.g. error message]

Unable to search the network on the phone

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]
My enb page does not set the sampling frequency.How to set the sampling frequency ?

**Comment by andrepuschmann** [comment]
Hey,
I suggest you have a look here first https://docs.srslte.com/en/latest/app_notes/source/cots_ue/source/index.html  Please feel free to open an issue with more precise explanation if you still have problems.
