### ISSUE TITLE
Some abnormal issue in srsepc

### ISSUE THREAD

**Issue by kongwenhua** [srsLTE/srsLTE#646]
I have configured a user data in csv file, the imsi is defined like 00101xxxxxxx, but every time i run srsepc and user access, it will show no imsi 00101xxxxxxx. Then I open the csv file, the imsi was changed 10101xxxxxxx, I can't understand why, maybe imsi starting with 0 is not allowed?

**Comment by andrepuschmann** [comment]
make sure to only edit the user data in the CSV when the EPC is NOT running. it will overwrite it when stopping. Hope that helps. Please reopen if issue still exists.
