### ISSUE TITLE
Get rid of B2XX frame* args

### ISSUE THREAD

**Issue by Agmagor** [srsLTE/srsLTE#65]
Hi,

I experienced a lot of situations (using cell_search and patched srsUE for SIB decoding) where I completely loose SDR control with errors like :

> ############
> Error opening RX stream: 33
> No compatible RF frontend found
> Error opening RF device
> Failed to find device auto with args auto
> ############

I then need to issue a `b2xx_fx3_utils -U` (USB subsystem reset) command to regain SDR functionnality

I never encountered the same error after removing the `recv_frame_size=9232,send_frame_size=9232` in rf_uhd_imp.cpp ; without affecting my basic usage of srsLTE / srsUE

AFAIK ; the only context in which I needed to tweak USB frame settings with the B200 was working with Amarisoft eNB for bandwidths <= 5MHz (and the frame sizes were tweaked with much lower values).

FYI the USB controller is an Intel / C230

**Comment by ismagom** [comment]
Hi, 

Yes you are probably right. We've been thinking of removing those for a while. I think that their impact in the performance is negligible. Will do that now and push to master. 

Thanks for catching this and the other bugs.
