### ISSUE TITLE
CMAKE_CXX_FLAGS vs CMAKE_C_FLAGS in CMakeLists.txt

### ISSUE THREAD

**Issue by Agmagor** [srsLTE/srsLTE#68]
Hi,

I've not studied this one for too long but I think it is an error:

In https://github.com/srsLTE/srsLTE/blob/master/CMakeLists.txt#L102 we set CMAKE_CXX_FLAGS if we are in a Debug build, and we set CMAKE_C_FLAGS when in Release.

**Comment by andrepuschmann** [comment]
I think this has been resolved in the new version. Thanks anyways.
