### ISSUE TITLE
FPGA

### ISSUE THREAD

**Issue by rand0mstring** [srsLTE/srsLTE#79]
Is there any thought towards / plan to push some performance hungry components to the FPGA-- (talking B210 but they all have them)? Could push SRS into smaller footprint, battery powered applications, besides making better general use of the hardware.

**Comment by andrepuschmann** [comment]
We don't have any plans to push significant processing back to the FPGA right now. While you are certainly right that this could offload the GPP quite a bit you are also losing the possibility of modifying things easily, one of the big advantages of SDRs.
