### ISSUE TITLE
Link error with libvolk.so

### ISSUE THREAD

**Issue by lrf8682004** [srsLTE/srsLTE#82]
If VOLK is NOT installed, then the whole process is good. However, if volk is compiled and installed, we have follow error message when we make srsLTE

[ 51%] Building C object lib/src/phy/mimo/test/CMakeFiles/layermap_test.dir/layermap_test.c.o
Linking C executable layermap_test
/usr/local/lib/libvolk.so: undefined reference to `tanhf'
/usr/local/lib/libvolk.so: undefined reference to `sinf'
/usr/local/lib/libvolk.so: undefined reference to `powf'
/usr/local/lib/libvolk.so: undefined reference to `hypotf'
/usr/local/lib/libvolk.so: undefined reference to `tanf'
/usr/local/lib/libvolk.so: undefined reference to `atanf'
/usr/local/lib/libvolk.so: undefined reference to `cosf'
/usr/local/lib/libvolk.so: undefined reference to `acosf'
/usr/local/lib/libvolk.so: undefined reference to `expf'
/usr/local/lib/libvolk.so: undefined reference to `log2f'
/usr/local/lib/libvolk.so: undefined reference to `rintf'
/usr/local/lib/libvolk.so: undefined reference to `sqrtf'
/usr/local/lib/libvolk.so: undefined reference to `pow'
/usr/local/lib/libvolk.so: undefined reference to `log10f'
/usr/local/lib/libvolk.so: undefined reference to `sqrt'
/usr/local/lib/libvolk.so: undefined reference to `sincosf'
/usr/local/lib/libvolk.so: undefined reference to `asinf'
/usr/local/lib/libvolk.so: undefined reference to `atan2f'
collect2: error: ld returned 1 exit status
make[2]: *** [lib/src/phy/mimo/test/layermap_test] Error 1
make[1]: *** [lib/src/phy/mimo/test/CMakeFiles/layermap_test.dir/all] Error 2
make: *** [all] Error 2

It seems that -lm is missing.
However taking a look at lib/src/phy/mimo/test/CMakeFiles/layermap_test.dir/link.txt, -lm has indeed been included into the linking command. 

It is quite confusing.

**Comment by andrepuschmann** [comment]
Hey, this is a mismatch of libvolk built on your system (likely an older version built with an older compiler) and the current srsLTE build. We recommend to rebuild libvolk or, better, delete your custom installation and install the version that comes with your system.
