### ISSUE TITLE
EPC that can work with srsLTE 

### ISSUE THREAD

**Issue by lrf8682004** [srsLTE/srsLTE#83]
Thanks for the wonderful project. 
It seems to make the two parts srsue/srsENB work together and have a complete LTE system, EPC part is still missing. Could you suggest a EPC software to work with both srsue and srsENB? Is there any open source implementation available?

Thanks!

**Comment by lrf8682004** [comment]
To make it more clearly,  I am only interested in the communication between UE and eNode. Is it possible to create the connection and communication between srsUE and srsENB without S1 interface(EPC)?

**Comment by andrepuschmann** [comment]
Hey, I am afraid such a mode without S1 isn't possible with srsENB right now.

**Comment by FFY00** [comment]
@andrepuschmann could you stil suggest an open source EPC? Thanks in advance.

**Comment by andrepuschmann** [comment]
Please check the mailing list for tips about EPCs. There has been a discussion about different alternatives just recently.
