### ISSUE TITLE
core dump issue with the srsue binary

### ISSUE THREAD

**Issue by razaborg** [srsLTE/srsLTE#84]
I tried to setup an LTE test environment with both: 
- the srsUE program using a **limeSDR** for the UE part
- the Amarisoft LTE 100EPC for the EPC part

I installed all the dependencies and everything compiled successfully, but during the cell attachment, just after the SIB2 has been received, I got a core dump error from the srsue binary...

I tried with both  VM (Ubuntu 17.04 kernel classic & lowlatency) and a bare computer (Ubuntu 16.04 kernel lowlatency).

Here is the log from the srsue binary : https://pastebin.com/jrMjinWU
And here is the end of the log file provided in debug mode : https://pastebin.com/d5uAwUgX
I can provide you the full file if you want to, but it's pretty huge...

So I don't have a clue about where does the issue can come from... Maybe you'll be able to help me with that ?

**Comment by ismagom** [comment]
srsUE does not currently support limeSDR. Only the receive only examples pdsch_ue, cell_search and cell_measurement are supported.
