### ISSUE TITLE
testing the srsLTE tools: ./mac_test

### ISSUE THREAD

**Issue by jarodcs** [srsLTE/srsLTE#87]
Hello huys, I hope I can find your knowledge in good mood for a little bit of help here :D 
Once installed, I was testing all the srsLTE executables like for example: 

srsue/test/phy$ sudo ./ue_itf_test_prach -c -f xxxx -F xxxx
srsue/test/mac$ sudo ./mac_test -G 70 -f xxxx -F xxxx

but I always get the error "Segmentation fault" after it prompts "Searching for cell..."
I am able to run the main executables like ./srsue o ./srsenb with zero problems and also I dont think Segmentatio Fault is a syntax message ... what am I doing wrong?

Thanks

**Comment by andrepuschmann** [comment]
Thanks for reporting. Fix has been pushed.
