### ISSUE TITLE
srsenb: ue will  disconnect in a few minutes after connecting to the srsenb

### ISSUE THREAD

**Issue by eric80s** [srsLTE/srsLTE#95]
We have added custom hardware rf_xxx_imp.c to srsLTE and tested our SDR hardware with SRSENB; The current test environment is Amarisoft EPC <---> SRSENB <----> UE;
During the test, we found that the UE would disconnect  in about a few minutes after connecting to the SRSENB, and filtering out a lot of warning information in ENB. Log, for example:
20:57:26.508541 [MAC ] Warning [03861] SCHED: discarting TB pid=5, tti=3861, maximum number of retx exceeded (4)
20:57:56.705789 [RRC ] Warning User rnti=0x46 expired Activity deadline: 30:8565>30:0 us

Can anyone give advice on how to solve this issue?
thanks

**Comment by dongxusb** [comment]
Hello,chaoeric! you solved the problem? Recently i am making a test like you , my test environment is OAI EPC <---> SRSENB <----> SRSUE. During the test,i met the same problem like you , SRSUE would disconnect in about a few minutes after connecting to the SRSENB, in the  terminal of  the computer  where SRSUE was installed will appear a lot of "L"  and "sync error" ,at the same time  in the  terminal of  the computer  where SRSENB was installed will give a advice "failed to connect to MME and make a try in 10 seconds".Can you give me some advise on this problem? thanks a lot.
