### ISSUE TITLE
Can this project be extended to implement NB-IoT?

### ISSUE THREAD

**Issue by desword** [srsLTE/srsLTE#98]
Can this project be extended to implement NB-IoT on USRP N210?

https://arxiv.org/pdf/1705.03529.pdf

I find that there is a paper describe this project can be used to implement NB-IoT.
However, I can not find the introduced component like nbiot_call_search module in example applications.

**Comment by ismagom** [comment]
Hi,

NB-IoT extensions are currently not available under the open source version. Please contact  sales@softwareradiosystems.com for more information.

**Comment by PhatHub** [comment]
@ismagom 
Hi! Are NB-IoT extensions still not available? I see that there are example UE and enodeb ... do those examples allow for running an NBIoT eNodeB testbed? Or does that still require the non-Open Source version?
Thanks!

> Hi,
> 
> NB-IoT extensions are currently not available under the open source version. Please contact [sales@softwareradiosystems.com](mailto:sales@softwareradiosystems.com) for more information.

**Comment by andrepuschmann** [comment]
There are basic NB-IoT examples for the UE in receive only mode. The full eNB is not available.
